### ISSUE TITLE
大佬开发兼容其它版本的测试呗

### ISSUE THREAD

**Issue by evolutionjay** [monlor/Monlor-Tools#1]
毕竟 Misstar Tools 作者受到了压力, 但他又不在GitHub 更新.

**Comment by monlor** [comment]
其他版本？ 你指的是小米其他路由？没有测试设备啊，最多考虑下小米路由器mini。

**Comment by steadyzeus** [comment]
请问有r3d能用吗？小米路由器HD ，能科学上网么？

**Comment by monlor** [comment]
r3d跟r2d差不多的，修改下可以用，但或多或少有点问题，需要测试。

**Comment by steadyzeus** [comment]
@monlor 大佬，能帮忙搞个r3的ssr 么

**Comment by monlor** [comment]
Misstar Tools工具箱里不是有么.

**Comment by nshen** [comment]
支持一下mini吧，我来帮测试
