### ISSUE TITLE
如何在路由器上安装一个简单浏览器？

### ISSUE THREAD

**Issue by linbren** [monlor/Monlor-Tools#10]
您好，如何在路由器上安装一个简单浏览器？
就是访问一个网页，可以取到路由器所在的IP(网页内置了定位API).

**Comment by linbren** [comment]
方便放出APP的二维码地址吗？
就是路由器管理里面可以直接扫描二维码安装插件的那个二维码。

**Comment by monlor** [comment]
你说的是官方的插件平台？权限很低，无法开发这些插件。如果仅仅获取ip没必要做一个网页吧。

**Comment by monlor** [comment]
路由器后台就可以获取外网ip。

**Comment by linbren** [comment]
其实就是想在路由器上运行网页版的APP。
如果有浏览器，就能达目的。

**Comment by monlor** [comment]
没太懂你的想法。
