### ISSUE TITLE
小米3G

### ISSUE THREAD

**Issue by guoguo882010** [monlor/Monlor-Tools#12]

**Comment by guoguo882010** [comment]
可以科学上网吗

**Comment by monlor** [comment]
你可以测试一下，目前R3上测试没问题。

**Comment by fivepart** [comment]
前几天3G还用得挺好的，然后今天就这样了：

********* ShadowSocks ***********
启动shadowsocks服务？[1/0] 1
shadowsocks节点：[1:*** 2:*** 3:***]
添加shadowsocks节点？[1/0] 0
修改shadowsocks配置(***, gfwlist)？[1/0] 1
shadowsocks节点：[1:*** 2:*** 3:***]
请选择shadowsocks节点：3
[1.gfwlist 2.whitelist 3.wholemode]
请选择shadowsocks模式：1
进入shadowsocks高级设置？[1/0] 0
ifconfig: eth0.2: error fetching interface information: Device not found
【ShadowSocks】: 关闭ss主进程...
/etc/rc.common: line 92: cru: not found
【ShadowSocks】: 清除iptables规则...
/etc/rc.common: line 92: cru: not found
【ShadowSocks】: 创建ss节点配置文件...
【ShadowSocks】: 开启dns2socks进程...
【ShadowSocks】: 加载iptables的nat规则...
iptables v1.4.12.2: host/network `' not found
Try `iptables -h' or 'iptables --help' for more information.
【ShadowSocks】: 加载ACL规则:其余主机模式为:科学上网
【ShadowSocks】: 启动ss主进程(***)...
【ShadowSocks】: 添加国外黑名单规则...
【ShadowSocks】: 启动shadowsocks服务完成！

**Comment by monlor** [comment]
不会吧，我3G都没测试过？工具箱更新了么

**Comment by fivepart** [comment]
重新安装后，仍然不能使用：

********* ShadowSocks ***********
启动shadowsocks服务？[1/0] 1
shadowsocks节点：[1:***]
添加shadowsocks节点？[1/0] 0
修改shadowsocks配置(空, 空)？[1/0] 1
shadowsocks节点：[1:***]
请选择shadowsocks节点：1
[1.gfwlist 2.whitelist 3.wholemode]
请选择shadowsocks模式：1
进入shadowsocks高级设置？[1/0] 1
删除shadowsocks节点？[1/0] 0
启动shadowsocks游戏模式？[1/0] 0
其余设备运行模式为: 科学上网
设置局域网代理控制？[1/0] 0
ifconfig: eth0.2: error fetching interface information: Device not found
【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 清除iptables规则...
【ShadowSocks】: 创建ss节点配置文件...
【ShadowSocks】: 开启dns2socks进程...
【ShadowSocks】: 加载iptables的nat规则...
iptables v1.4.12.2: host/network `' not found
Try `iptables -h' or 'iptables --help' for more information.
【ShadowSocks】: 加载ACL规则:其余主机模式为:科学上网
【ShadowSocks】: 启动ss主进程(us6)...
【ShadowSocks】: 添加国外黑名单规则...
【ShadowSocks】: 启动shadowsocks服务完成！

结果仍然是不行

咋联系你？

**Comment by monlor** [comment]
3G没人帮我测试过，有兴趣的话加我QQ：421599756

**Comment by monlor** [comment]
你的问题应该是跟其他型号不一样，识别不出eth0.2网卡，你可以试试白名单模式。
