### ISSUE TITLE
R3P ss设置 － Monlor Tools版本：2.2.8

### ISSUE THREAD

**Issue by dicksonboy** [monlor/Monlor-Tools#13]
********* ShadowSocks ***********
启动shadowsocks服务？[1/0] 1
shadowsocks节点：[1:ss]
添加shadowsocks节点？[1/0] 0
修改shadowsocks配置(ss, gfwlist)？[1/0] 0
进入shadowsocks高级设置？[1/0] 0
ifconfig: eth0.2: error fetching interface information: Device not found
【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 清除iptables规则...
【ShadowSocks】: 创建ss节点配置文件...
【ShadowSocks】: 开启dns2socks进程...
【ShadowSocks】: 加载iptables的nat规则...
iptables v1.4.12.2: host/network `' not found
Try `iptables -h' or 'iptables --help' for more information.
【ShadowSocks】: 加载ACL规则:其余主机模式为:科学上网
【ShadowSocks】: 启动ss主进程(ss)...
【ShadowSocks】: 添加国外黑名单规则...
【ShadowSocks】: 启动shadowsocks服务完成！

當我返回到主菜单又會變成
1. shadowsocks[未运行]

請指導一下

**Comment by monlor** [comment]
不好意思，R3P我没测试过，有兴趣帮我测试的话可以加我qq:421599756
