### ISSUE TITLE
R3 配置完shadowsocks出错，进到grep 里面就停了

### ISSUE THREAD

**Issue by wangnanlena** [monlor/Monlor-Tools#14]
【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 清除iptables规则...
【ShadowSocks】: 创建ss节点配置文件...
BusyBox v1.19.4 (2018-02-02 14:55:39 CST) multi-call binary.

Usage: grep [-HhnlLoqvsriwFE] [-m N] [-A/B/C N] PATTERN/-e PATTERN.../-f FILE [FILE]...

Search for PATTERN in FILEs (or stdin)

        -H      Add 'filename:' prefix
        -h      Do not add 'filename:' prefix
        -n      Add 'line_no:' prefix
        -l      Show only names of files that match
        -L      Show only names of files that don't match
        -c      Show only count of matching lines
        -o      Show only the matching part of line
        -q      Quiet. Return 0 if PATTERN is found, 1 otherwise
        -v      Select non-matching lines
        -s      Suppress open and read errors
        -r      Recurse
        -i      Ignore case
        -w      Match whole words only
        -F      PATTERN is a literal (not regexp)
        -E      PATTERN is an extended regexp
        -m N    Match up to N times per file
        -A N    Print N lines of trailing context
        -B N    Print N lines of leading context
        -C N    Same as '-A N -B N'
        -e PTRN Pattern to match
        -f FILE Read pattern from file

**Comment by monlor** [comment]
ss配置添加的可能有问题，把你的配置过程复制给我看看，重新添加一下节点。

**Comment by wangnanlena** [comment]
去看了script，看起来应该是id没set。我的添加过程如下（server address有做处理）


启动shadowsocks服务？[1/0] 1
shadowsocks节点：[空]
添加shadowsocks节点？[1/0] 1
输入shadowsocks(r)节点名：ss2
输入shadowsocks服务器地址：ss2.MYSERVER.com
输入shadowsocks服务器端口：5108
输入shadowsocks服务器密码：test
输入shadowsocks加密方式：aes-256-cfb
输入shadowsocks协议(protocols)：shadowsocks
输入shadowsocks混淆（obfs）：
确定要添加配置：ss2,ss2.MYSERVER,5108,test,aes-256-cfb,shadowsocks,？[1/0] 1
添加完成，再添加一个？[1/0] 0
修改shadowsocks配置(空, 空)？[1/0] 0
进入shadowsocks高级设置？[1/0] 0
【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 清除iptables规则...




-----------------------
uci show看了一下，id没添加上，不知道什么原因

root@XiaoQiang:(unknown)# uci show monlor
monlor.tools=config
monlor.tools.userdisk=/etc/monlor
monlor.tools.path=/etc/monlor
monlor.tools.url=https://coding.net/u/monlor/p/Monlor-Tools/git/raw/master
monlor.shadowsocks=config
monlor.shadowsocks.service=ShadowSocks
monlor.shadowsocks.enable=1

**Comment by monlor** [comment]
我的配置没用uci储存，“修改shadowsocks配置(空, 空)？[1/0] 0”这一步你没配置，需要配置使用节点跟运行模式。

**Comment by monlor** [comment]
如果不是ssr，协议混淆直接回车

**Comment by wangnanlena** [comment]
运行成功了，814 root      3092 S    /etc/monlor/apps/shadowsocks/bin/ss-local -c /etc/monlor/apps
18850 root      2996 S    /etc/monlor/apps/shadowsocks/bin/ss-redir -b 0.0.0.0 -c /etc/
也都在，但fq不成功

**Comment by monlor** [comment]
运行过程中没有任何报错？确认你的账号没有问题，monlor命令里面状态正常？

**Comment by wangnanlena** [comment]
测了一下模式，似乎是gfw mode有问题，whitelist和whole是好的...

**Comment by wangnanlena** [comment]
这几条似乎没执行？
	ipset -N gfwlist iphash -!
	iptables -t nat -A SHADOWSOCK -p tcp -m set --match-set customize_black dst -j REDIRECT --to-port 1081
	iptables -t nat -A SHADOWSOCK -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1081

我用iptables -L看没看到1081 redirect相关的规则……

**Comment by wangnanlena** [comment]
不对，还是生效了...
iptables -L -t nat可以查到...不知道为什么了，你的路由器上可以用gfw 模式吗

**Comment by wangnanlena** [comment]
反复添加了几次后，重启完莫名其妙又好了...非常感谢

**Comment by monlor** [comment]
好吧，感谢测试。
