### ISSUE TITLE
装了之后路由器频繁掉线

### ISSUE THREAD

**Issue by daizy008** [monlor/Monlor-Tools#15]
只装了这一个，且只装了 Aria2，没装其他插件。
用的是 R1D。
每次掉线都要重启路由才行。。。

**Comment by monlor** [comment]
你确定是工具箱造成的吗？还是aria2造成的，我R2D用的挺稳定的。是指网掉线？

**Comment by daizy008** [comment]
不装aria2时很稳定。
装了之后每三四小时都会就会断外网。

**Comment by monlor** [comment]
这个问题我也没遇到过，你可以试试更换一下配置文件试试。配置文件保存在： `/etc/monlor/apps/aria2/config/aria2.conf`，推荐你试试这个：`https://raw.githubusercontent.com/acgotaku/BaiduExporter/master/aria2c/aria2.conf`

**Comment by daizy008** [comment]
似乎是我之前装的 Miwifi Plus的问题和monlor无关
