### ISSUE TITLE
aria2 安装配置后还是提示未运行

### ISSUE THREAD

**Issue by michealhansun** [monlor/Monlor-Tools#16]

**Comment by michealhansun** [comment]
还有想问下安装好之后再哪个地址管理下载任务

**Comment by michealhansun** [comment]
小米路由3

**Comment by monlor** [comment]
小米路由器3测试过没问题的，你重启一下试试，贴一下你的运行过程。

**Comment by michealhansun** [comment]
********* Aria2 ***********
启动aria2服务？[1/0] 1
修改aria2端口号(6800)？[1/0] 0
修改aria2配置(aria2, aria2, /extdisks/sda1/下载)？[1/0] 1
请输入aria2用户名(回车表示不设置)：aria2
请输入aria2密码(回车表示不设置)：aria2
请输入aria2下载路径(回车默认/extdisks/sda1/下载)：
【Aria2】: 正在停止aria2服务... 
【Aria2】: 正在启动aria2服务... 
【Aria2】: 加载aria2配置...
【Aria2】: 启动aria2服务完成！

**Comment by michealhansun** [comment]
**** Monlor Tools工具箱 ****
********************************
当前版本：2.2.27.2 最新版本：2.2.27.2

0. 工具箱/插件管理(Ctrl + c退出)
1. shadowsocks[ss节点: google(gfwlist)]
2. koolproxy[选择以安装]
3. aria2[未运行]

----
ARIA2 未运行，这是表示没配置好吗

**Comment by monlor** [comment]
运行1. export LD_LIBRARY_PATH=/usr/lib:/lib:/etc/monlor/apps/aria2/lib
2. /etc/monlor/apps/aria2/bin/aria2
运行完报错贴给我看看。

**Comment by michealhansun** [comment]
root@XiaoQiang:~# export LD_LIBRARY_PATH = / usr / lib：/ lib：/ etc / monlor / apps /
 aria2 / lib
-ash: export: : bad variable name
root@XiaoQiang:~# 
root@XiaoQiang:~# / etc / monlor / apps / aria2 / bin / aria2
-ash: /: Permission denied

**Comment by michealhansun** [comment]
root@XiaoQiang:~# export LD_LIBRARY_PATH=/usr/lib:/lib:/etc/monlor/apps/aria2/lib
root@XiaoQiang:~# /etc/monlor/apps/aria2/bin/aria2
Specify at least one URL.
Usage: aria2c [OPTIONS] [URI | MAGNET | TORRENT_FILE | METALINK_FILE]...
See 'aria2c -h'.

**Comment by monlor** [comment]
运行cat /etc/monlor/apps/aria2/config/aria2.conf 看看

**Comment by michealhansun** [comment]
#Aria2 configuration

# RPC Setting
#
enable-rpc=true
rpc-listen-all=true
rpc-allow-origin-all=true
rpc-listen-port=6800
rpc-user=aria2
rpc-passwd=aria2


# General Setting
#
dir=/extdisks/sda1/下载
input-file=/etc/aria2.session
save-session=/etc/aria2.session
save-session-interval=60
#event-poll=select
disk-cache=8M
#enable-mmap=true
file-allocation=trunc
peer-id-prefix=-UT2210-
user-agent=uTorrent/2210(25130)

# Connection Setting
#
continue=true
max-connection-per-server=5
max-concurrent-downloads=3
min-split-size=1M
split=5
max-overall-download-limit=0
max-overall-upload-limit=50K
max-upload-limit=20
lowest-speed-limit=20K
auto-save-interval=120
check-certificate=false

# BT/PT Setting
#
bt-require-crypto=true
bt-max-peers=300
enable-peer-exchange=true
bt-enable-lpd=true
enable-dht=true
listen-port=48028
dht-listen-port=48028
follow-torrent=true
force-save=true
bt-seed-unverified=true
bt-save-metadata=true
bt-hash-check-seed=true
bt-remove-unselected-file=false
bt-stop-timeout=900
seed-ratio=1
seed-time=525600
bt-tracker=udp://tracker.coppersurfer.tk:6969/announce,udp://tracker.leechers-paradise.org:6969/announce,udp://tracker.opentrackr.org:1337/announce,udp://tracker.zer0day.to:1337/announce,udp://9.rarbg.com:2710/announce,udp://p4p.arenabg.com:1337/announce,udp://explodie.org:6969/announce,udp://tracker.mg64.net:6969/announce,udp://mgtracker.org:2710/announce,udp://tracker.yoshi210.com:6969/announce,udp://tracker.tiny-vps.com:6969/announce,udp://tracker.skyts.net:6969/announce,udp://tracker.tordb.ml:6881/announce,udp://tracker.piratepublic.com:1337/announce,udp://tracker.grepler.com:6969/announce,udp://tracker.filetracker.pl:8089/announce,udp://tracker.edoardocolombo.eu:6969/announce,udp://ipv4.tracker.harry.lu:80/announce,udp://91.218.230.81:6969/announce,udp://tracker.vanitycore.co:6969/announce,udp://tracker.kuroy.me:5944/announce,udp://zephir.monocul.us:6969/announce,udp://tracker.desu.sh:6969/announce,udp://bt.xxx-tracker.com:2710/announce

**Comment by monlor** [comment]
运行这个呢 /etc/monlor/apps/aria2/bin/aria2 --conf-path=/etc/monlor/apps/aria2/config/aria2.conf

**Comment by monlor** [comment]
等我更新

**Comment by michealhansun** [comment]
ok

2018-03-06 11:16 GMT+08:00 Chaco Green <notifications@github.com>:

**Comment by monlor** [comment]
我更新到测试版源了，你换下源更新aria2试试

**Comment by michealhansun** [comment]
启动aria2服务？[1/0] 1
修改aria2端口号(6800)？[1/0] 
修改aria2配置(空, /extdisks/sda1/下载)？[1/0] 0
【Aria2】: 正在停止aria2服务... 
【Aria2】: 正在启动aria2服务... 
【Aria2】: 加载aria2配置...
【Aria2】: 生成aria2本地web页面
ln: /www/aria2: No space left on device
【Aria2】: 启动aria2服务完成！
【Aria2】: 访问http://192.168.31.1/aria2管理服务
【Aria2】: jsonrpc地址:http://192.168.31.1:6800/jsonrpc
----
我的路由空间容量不足了？

**Comment by monlor** [comment]
没事，可能/www目录不让写入，只要运行正常，你在aria2c.com里管理也可以的

**Comment by michealhansun** [comment]
错误: Aria2 RPC 服务器错误

**Comment by monlor** [comment]
哪里提示这个错误？有兴趣加我qq我给你远程一下吧，421599756。

**Comment by michealhansun** [comment]
前两天试了还是不行，这几天忙，过几天给你远程帮忙看下

**Comment by monlor** [comment]
小米路由3 aria2应该正常了。
