### ISSUE TITLE
ShadowSocks连不上啊

### ISSUE THREAD

**Issue by xxzj990** [monlor/Monlor-Tools#18]
设备是小米路由器3，版本是：2.25.36

**Comment by monlor** [comment]
状态正常么？

**Comment by xxzj990** [comment]
显示已启动

**Comment by xxzj990** [comment]
协议和混淆分别写的origin和plain，可以吗？

**Comment by xxzj990** [comment]
我连的是域名可以吗？是只能连ip吗

**Comment by monlor** [comment]
你如果用的ss不是ssr不要写协议和混淆，可以用域名

**Comment by xxzj990** [comment]
@monlor 好的我试试

**Comment by xxzj990** [comment]
@monlor 可以连上了，但是不知道为什么只能用wholemode模式，gfw模式连不上

**Comment by monlor** [comment]
白名单应该可以的，gfwlist不清楚你们什么情况，我的R2D挺正常的。

**Comment by xxzj990** [comment]
@monlor 我的也正常了，是mac浏览器设置问题，换浏览器可以了

**Comment by monlor** [comment]
可能要清除缓存
