### ISSUE TITLE
求尝试支持 R3P，我可以帮测试哈，谢谢

### ISSUE THREAD

**Issue by lisuyong** [monlor/Monlor-Tools#2]
RT，真心感谢，哥们等你好久啦  👍

**Comment by monlor** [comment]
我做的这个插件中心跟Misstar Tools没得比，为啥不用他的呢？

**Comment by lisuyong** [comment]
主要因为他们那个太久不更新了哈，实在是遗憾

**Comment by monlor** [comment]
我做的主要是依靠配置文件来管理插件，没有web图形化界面，这点你清楚吗？ 要做的话，我可以尝试一下。

**Comment by lisuyong** [comment]
给力啊，没有问题的，您能帮尝试就是最大的帮助了～ 哈哈，我也是程序员
