### ISSUE TITLE
shadowsocks[未运行]，前两天更新后，服务无法启动，小米路由3

### ISSUE THREAD

**Issue by michealhansun** [monlor/Monlor-Tools#22]
请输入你的选择(exit退出)：
********* ShadowSocks ***********
启动shadowsocks服务？[1/0] 1
shadowsocks节点：[1.g]
添加shadowsocks节点？[1/0] 0
修改shadowsocks配置(g, gfwlist)？[1/0] 0
进入shadowsocks高级设置？[1/0] 0
【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 清除iptables规则...
【ShadowSocks】: 创建ss节点配置文件...
【ShadowSocks】: 开启dns2socks进程...
【ShadowSocks】: 加载iptables的nat规则...
【ShadowSocks】: 加载ACL规则:其余主机模式为:科学上网
【ShadowSocks】: 启动ss主进程(g)...
【ShadowSocks】: 添加国外黑名单规则...
【ShadowSocks】: 启动shadowsocks服务完成！

**Comment by michealhansun** [comment]
********************************
  **** Monlor Tools工具箱 ****
********************************
当前版本：2.3.23.1 最新版本：2.3.23.1

0. 管理菜单(Ctrl + c退出)
1. shadowsocks[未运行]
2. koolproxy[选择以安装]
3. aria2[选择以安装]
4. vsftpd[选择以安装]
5. kms[选择以安装]
6. frpc[运行服务器: ****]
7. ngrok[选择以安装]
8. webshell[选择以安装]
9. tinyproxy[选择以安装]
10. verysync[选择以安装]
11. fastdick[选择以安装]
12. firewall[选择以安装]

**Comment by mezhangyes** [comment]
一样

**Comment by monlor** [comment]
这是上个版本状态显示有问题，实际使用是正常的，当前版本应该没问题了。

**Comment by mezhangyes** [comment]
就算是显示有问题 还是连不上网

**Comment by monlor** [comment]
是小米路由3吗？能否粘贴出你的配置过程，包括添加节点？（隐藏一下ss信息）

**Comment by mezhangyes** [comment]
R1CM

**Comment by mezhangyes** [comment]
启动shadowsocks服务？[1/0] 1
shadowsocks节点：[空]
添加shadowsocks节点？[1/0] 1
输入shadowsocks(r)节点名：kin
输入shadowsocks服务器地址：
输入shadowsocks服务器端口
输入shadowsocks服务器密码：
输入shadowsocks加密方式：aes-256-gcm
输入shadowsocks协议(protocols)：
输入shadowsocks混淆（obfs）：
确定要添加节点：kin,202.5.21.2,22409,KindomZWB,aes-256-gcm,,？[1/0] 1
添加完成，再添加一个？[1/0] 0
修改shadowsocks配置(KIN, gfwlist)？[1/0] 0
进入shadowsocks高级设置？[1/0] 0
【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 清除iptables规则...
【ShadowSocks】: 创建ss节点配置文件..

现在又卡在这里了

**Comment by mezhangyes** [comment]
协议要写吗

**Comment by monlor** [comment]
如果不是ssr不用写，别暴露ss账号了啊

**Comment by mezhangyes** [comment]
启动shadowsocks服务？[1/0] 1
shadowsocks节点：[1.kin]
添加shadowsocks节点？[1/0] 1^H0
修改shadowsocks配置(KIN, gfwlist)？[1/0] 1
shadowsocks节点：[1.kin]
请选择shadowsocks节点：1
[1.gfwlist 2.whitelist 3.wholemode]
请选择shadowsocks模式：3
进入shadowsocks高级设置？[1/0] 0
【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 清除iptables规则...
【ShadowSocks】: 创建ss节点配置文件...
【ShadowSocks】: 开启dns2socks进程...
【ShadowSocks】: 加载iptables的nat规则...
【ShadowSocks】: 加载ACL规则:其余主机模式为:科学上网
【ShadowSocks】: 启动ss主进程(kin)...
【ShadowSocks】: 添加全局模式iptables规则...
【ShadowSocks】: 启动shadowsocks服务完成！
返回主菜单？[1/0] 
root@XiaoQiang:~#

**Comment by mezhangyes** [comment]
完成后还是用不了

**Comment by mezhangyes** [comment]
未运行

**Comment by mezhangyes** [comment]
出现了这个 iptables: No chain/target/match by that name.

**Comment by monlor** [comment]
等我更新

**Comment by mezhangyes** [comment]
麻烦大佬了

**Comment by monlor** [comment]
更换测试版源，更新ss插件，不支持aes-256-gcm加密。

**Comment by mezhangyes** [comment]
请输入你的选择：9
1. coding下载源
2. github下载源
3. coding测试源(不建议)
请选择下载源：3
【Tools】: 获取版本更新脚本启动...
【Tools】: 获取更新插件列表
【Tools】: 获取插件版本信息


额。。不动了

**Comment by mezhangyes** [comment]
牛批 ！！

**Comment by wo20ljj** [comment]
支持你一下，但是我觉得你可以改个工具箱名字，原版MT，太恶心了！发个VPS活动分享链接就被踢了！更恶心的是，发表情也被踢的！还把最有用的插件加锁！也是醉了！！

**Comment by monlor** [comment]
MT去掉ss插件也是无奈之举，可能作者没时间，群没怎么管理了。
