### ISSUE TITLE
如何更新白名单

### ISSUE THREAD

**Issue by avk458** [monlor/Monlor-Tools#24]
能否设置自动更新
`root@XiaoQiang:~# /etc/monlor/apps/shadowsocks/script/updaterules.sh
【ShadowSocks】: 更新shadowsocks分流规则
【ShadowSocks】: 更新大陆白名单规则失败`

**Comment by monlor** [comment]
可能是链接失效了，等我更新换一个链接。

**Comment by avk458** [comment]
如何添加自定义规则呢？

**Comment by monlor** [comment]
你可以编辑 /etc/monlor/apps/shadowsocks/config/customize_black.conf 或者/etc/monlor/apps/shadowsocks/config/customize_white.conf 这两个配置文件，分别是黑白名单规则。

**Comment by avk458** [comment]
gfwlist模式下，如何解决tg登陆不了的问题？代理模式下设置为127.0.0.1 1082也不行

**Comment by monlor** [comment]
你如果是手机电脑等设备，代理模式设置192.168.31.1 1082，如果你要用gfwlist黑名单模式，配置文件里只能添加域名。你可以试试这种方式：`ipset add gfwlist 91.108.56.0/22
ipset add gfwlist 91.108.4.0/22
ipset add gfwlist 109.239.140.0/24
ipset add gfwlist 149.154.160.0/20`，如果需要开机生效，保存到/etc/monlor/scripts/userscript.sh即可。
