### ISSUE TITLE
回国模式黑名单修改存在漏洞

### ISSUE THREAD

**Issue by hwanginpen** [monlor/Monlor-Tools#27]
你好，

前提： 回国模式下，不添加任何黑白名单，访问 baidu.com 和 whatismyipaddress.com 均显示直连ip，访问 ipip.net 显示节点信息。仅对路由器中的一台电脑科学上网，其余设备不走科学上网。

经测试，回国模式下shadowsocks的黑名单列表我分别添加了以下两个地址：
baidu.com
whatismyipaddress.com

1、启动shadowsocks后，确实强制这两个网址走了节点，查询的ip也是节点，正常工作。

2、当我直接选择0关闭shadowsocks 后，却发现 baidu.com 和 whatismyipaddress.com 均无法通过直连的方式打开（无法正常打开这两个网址）；重新开启shadowsocks功能时，这两个网址又可以正常打开。不断重复测试，最终结果是： shadowsocks 开启时，黑名单列表的这两个网址能通过节点方式打开网页，其他网站可以正常访问；shadowsocks 关闭时，无法正常访问这两个网站，其他网站可以正常访问。

3、经过以上的一番折腾，尝试修改黑名单列表，通过覆盖添加的方式，添加了空白行，替代了以上的两个网址，理论上不再对其强制走节点，但开启 shadowsocks 后，访问这两个网页仍通过节点。

4、最终尝试卸载了 shadowsocks 插件再重装
添加节点信息后，不添加黑白名单，回归正常：访问 baidu.com 和 whatismyipaddress.com 均显示直连ip，访问 ipip.net 显示节点信息； 添加黑名单，可强制 百度 和 whatismyipaddress.com 走节点。
但仍存在关闭ss无法访问黑名单网址 以及 删除/覆盖黑名单无效（之前添加的网址仍然走节点） 的情况。

希望作者能修复一下这个问题，谢谢！

**Comment by monlor** [comment]
之前有点小BUG，不知道是否是这个影响。我测试了一下，关闭ss无法访问黑名单的现象不存在，删除黑名单无效可能浏览器或你访问的网址没更新你的ip信息。我测试的是增加黑白名单后，电脑显示有问题，手机正常。比如添加baidu.com白名单，显示当地ip，添加whatismyipaddress.com黑名单，显示代理ip。
