### ISSUE TITLE
希望科学上网添加混淆参数设置

### ISSUE THREAD

**Issue by dongmiansongshu** [monlor/Monlor-Tools#28]
用的ssr是有混淆参数的，但是现在的只能设置混淆，而无法设置混淆参数，希望加入下。多谢喽

**Comment by monlor** [comment]
测试源已添加ssr的混淆参数，我没用过混淆参数，不知道是否生效，你可以测试一下。

**Comment by dongmiansongshu** [comment]
多谢了，mi3已测试，可以正常使用
