### ISSUE TITLE
你好  重启设备后后 aria2配置丢失 正在下载的东西也全没了 

### ISSUE THREAD

**Issue by yilin101** [monlor/Monlor-Tools#29]
你好  重启设备后后 aria2配置丢失 正在下载的东西也全没了 

这个问题怎么解决呢

**Comment by monlor** [comment]
是配置文件被清空了？还是下载记录没了。设备是什么型号呢？

**Comment by yilin101** [comment]
配置文件被清空了  正在下载和已经下载的记录都没了 小米路由2 白色带硬盘的那款

好不容易找到个能运行的aria2 不容易啊  结果试一下重启 发现这个问题

**Comment by monlor** [comment]
`appmanage.sh upgrade aria2 -f`
你试试更新下aria2，然后再重启一下，测试看会不会有问题，你也可以试试测试版

**Comment by yilin101** [comment]
好的 我试试

**Comment by yilin101** [comment]
你好 试了 重启还是数据没了

**Comment by monlor** [comment]
你确定是`/etc/monlor/apps/aria2/conf/aria2.conf`这个配置文件被清空了？

**Comment by yilin101** [comment]
不是清空 应该是恢复默认了  比如我设置了bt服务器地址  重启后就没了

**Comment by monlor** [comment]
不应该啊，工具箱脚本不会重置aria2配置的，添加bt服务器配置追加到aria2配置文件末尾

**Comment by yilin101** [comment]
我改了同时下载任务数5-->6
重启又恢复成5了

我也不知道为什么 好像aria2经常有这个情况。之前在群晖docker里面安装ariang 也这样 换了其他版本的才解决 但是不知道问题出在哪里

**Comment by monlor** [comment]
你在网页里改的配置？

**Comment by yilin101** [comment]
是的 
就算什么都不改 重启后 下载的记录也没了 好奇怪

**Comment by monlor** [comment]
可能下载记录没保存下来，等我更新吧

**Comment by yilin101** [comment]
save-session-interval=60
force-save
input-file=
save-session=


这个网上查的

**Comment by monlor** [comment]
你着急可以先改一下，/etc/aria2.session，我之前版本的配置文件加了的，后来改配置文件忘了加

**Comment by yilin101** [comment]
好的 
你大概什么时候更新

**Comment by yilin101** [comment]
好的 那我在现在版本上手动改改看
因为要给家人用的 他们不太懂这个 测试版问题多的话 到时候我远程不好弄了

**Comment by monlor** [comment]
`echo -e "input-file=/etc/aria2.session\nsave-session=/etc/aria2.session\nsave-session-interval=60" >> /etc/monlor/apps/aria2/conf/aria2.conf`

**Comment by yilin101** [comment]
-ash: can't create /etc/monlor/apps/aria2/conf/aria2.conf: nonexistent directory

**Comment by yilin101** [comment]
应该是config吧

**Comment by monlor** [comment]
额，不好意思，打错了，是config。`echo -e "input-file=/etc/aria2.session\nsave-session=/etc/aria2.session\nsave-session-interval=60" >> /etc/monlor/apps/aria2/config/aria2.conf`

**Comment by yilin101** [comment]
嗯 我已经在测试了 一会儿给你答复

**Comment by monlor** [comment]
`curl -Lo /etc/monlor/apps/aria2/config/aria2.conf https://coding.ne
t/u/monlor/p/Monlor-Test/git/raw/master/apps/aria2/config/aria2.conf`

**Comment by yilin101** [comment]
你好 aria2.session 可以了 重启后下载任务还在 
但是aria2.conf 在网页改的一些配置重启后还是不在  我看了一下在网页改了后 这个文件没变化 权限也改成777了

**Comment by monlor** [comment]
网页上的配置改了应该是无法生效的，要改配置的话，建议你直接改配置文件

**Comment by yilin101** [comment]
应该只能手动改配置问题  可能网页端没法改配置的吧

**Comment by yilin101** [comment]
好的 明白了  
真是太感谢了

**Comment by yilin101** [comment]
还有几个问题
1、小米路由的web页面经常打不打，或者登陆不了
2、同时用monlor 查看状态 aria2 显示未运行 实际有在运行
3、同时有的时候monlor 一片空白 获取不到任何信息

**Comment by yilin101** [comment]
![QQ拼音截图20180509164842.png](https://i.loli.net/2018/05/09/5af2b60b338ab.png)

**Comment by yilin101** [comment]
需要重启才能恢复正常

**Comment by monlor** [comment]
好的，这些问题我会好好看看的

**Comment by yilin101** [comment]
好的 谢谢

**Comment by monlor** [comment]
web页面打不开或登陆不了，这个应该与工具箱无关。可能CPU或内存占用高了。

**Comment by yilin101** [comment]
好吧  我在测试下载稳定性 5个任务下载 也不多吧

**Comment by monlor** [comment]
多，路由器CPU性能极差。samba随便复制文件，CPU就跑满。

**Comment by yilin101** [comment]
好吧 可能群晖用习惯了 
但是目测cpu都在10%以内

**Comment by yilin101** [comment]
我1515+群晖 都是十几个任务往里面干 哈哈

**Comment by monlor** [comment]
性能太差，想用个verysync都经常死机。

**Comment by yilin101** [comment]
我改成最多三个任务了 
可能确实路由性能不行吧 我昨天安装 KodExplore也没成功

**Comment by yilin101** [comment]
我主要是想把aria2折腾稳定后 就把路由寄回去 怕万一出问题 家人不会弄

**Comment by yilin101** [comment]
![QQ拼音截图20180509170835.png](https://i.loli.net/2018/05/09/5af2babe56cec.png)
还是这样 
连正常上网网页都会打不开 郁闷

**Comment by monlor** [comment]
KodExplore要先装entware。
`2、同时用monlor 查看状态 aria2 显示未运行 实际有在运行
3、同时有的时候monlor 一片空白 获取不到任何信息`
这两个问题中，第一个问题出现的时候运行`cat /tmp/pstmp.txt | grep aria2`，给我看看
第二个问题运行`cat /etc/monlor/config/applist*`，给我看看

**Comment by monlor** [comment]
你说的问题我都没出现过，也不能确定。网页打不开运行`cat /tmp/messages`

**Comment by yilin101** [comment]
![QQ拼音截图20180509171123.png](https://i.loli.net/2018/05/09/5af2bb6809b56.png)

**Comment by yilin101** [comment]
看到这样的字眼 
2017-10-21T01:25:53+08:00 (none) rmonitor[Server]: [11783]: System used memory too high!

**Comment by monlor** [comment]
你有电脑方便远程么

**Comment by yilin101** [comment]
内存可能太高了

**Comment by yilin101** [comment]
可以

**Comment by yilin101** [comment]
693 113 934 

73wg5q


teamview

**Comment by monlor** [comment]
等会，我在装teamviewer

**Comment by yilin101** [comment]
好的 麻烦你了

**Comment by monlor** [comment]
连接不上，你重开一下

**Comment by yilin101** [comment]
cxf186

**Comment by yilin101** [comment]
密码

**Comment by monlor** [comment]
你这个curl下载有问题，你是什么版本的固件。

**Comment by yilin101** [comment]
你好 刚出重装了 curl是正常了下载 没提示错误了
在只安装了aria2 ，两个下载任务
其他都没安装的情况下 
还是出现昨天的问题

**Comment by yilin101** [comment]
这台路由我用了两三年了 很稳定
都没遇到过这个问题  机子应该没问题
唯一一个就是最近刚换的8T硬盘 
我一会儿卸载了 什么都不装看看怎么回事 
会不会很磁盘有关系

**Comment by yilin101** [comment]
你好 卸载后就没问题了 郁闷

**Comment by monlor** [comment]
卸载8T硬盘就好了？

**Comment by yilin101** [comment]
没有 
是把monlor 卸载了 
一直到现在2个多小时候 
路由器都很正常

**Comment by yilin101** [comment]
我原来用www.misstar.com 他的aria2   唉 就是不知道为什么下载不了

**Comment by monlor** [comment]
你卸载了工具箱，curl正常？

**Comment by yilin101** [comment]
重装系统后 就已经正常了   
我把工具箱卸载后 路由器都稳定了
