### ISSUE TITLE
R3P 安裝失敗

### ISSUE THREAD

**Issue by luzhaohui** [monlor/Monlor-Tools#3]
SSH 到小米路由器Pro (R3P)，用懶人命令執行，依提示按任意鍵繼續，安裝失敗。

提示信息：
下载工具箱文件...
解压工具箱文件
文件解压失败！

**Comment by monlor** [comment]
运行 curl -skLo /tmp/monlor.zip https://coding.net/u/monlor/p/Monlor-Tools/git/raw/master/appstore/monlor.zip    试试，看能否下载成功。

**Comment by luzhaohui** [comment]
下载是成功的

**Comment by monlor** [comment]
unzip /tmp/monlor.zip -d /tmp 再解压呢

**Comment by luzhaohui** [comment]
@monlor 失败，没有unzip命令😄

**Comment by monlor** [comment]
没有unzip命令？等我搞成tar压缩的吧。

**Comment by luzhaohui** [comment]
@monlor 确实不可思议。等你发新的安装脚本

**Comment by monlor** [comment]
已更新，再测试一下

**Comment by luzhaohui** [comment]
@monlor 下载解压都正常了，但最后还是有问题，提示如下：

下载工具箱文件...
解压工具箱文件
初始化工具箱
/extdisks/sda2/.monlor.conf: source: line 3: base.sh: not found
工具箱安装完成!
请前往小米路由器/extdisks/sda2目录，编辑隐藏文件.monlor.conf配置工具箱.

**Comment by monlor** [comment]
能运行到这一步，差不多没问题了，刚修复了下这个问题，运行uninstall.sh卸载后重装一下。

**Comment by luzhaohui** [comment]
@monlor 安装正常了。不过没有UI，配置很不便利。

**Comment by monlor** [comment]
等有时间会增加web页面的😏
