### ISSUE TITLE
翻墙回国模式以及广告过滤插件存在问题

### ISSUE THREAD

**Issue by darkfky** [monlor/Monlor-Tools#30]
开启全局模式翻墙成功,开回国模式访问YOUTUBE等需要翻墙网站则都访问不了

广告过滤不管是全局模式还是视频模式,均过滤广告失败,另一个重点 (规则: 2020-5-6 00:00)   似乎规则更新不成功

**Comment by monlor** [comment]
回国模式不是用来翻墙，是给海外用户访问国内网站用的。规则日期是kp自己的问题，kp过滤视频广告经常会失效，请多测试几个视频网站。
