### ISSUE TITLE
R1D，Aria2下载磁力链接，每次下载2分钟左右挂死，Aria2状态显示未连接，过几分钟后又恢复，然后又再挂死。

### ISSUE THREAD

**Issue by lu989898** [monlor/Monlor-Tools#32]

**Comment by monlor** [comment]
由于没有测试设备，无法保证插件运行正常。

**Comment by lu989898** [comment]
请问如何测试设备，有指导手册么。

**Comment by monlor** [comment]
会有的

**Comment by lu989898** [comment]
我设置了个每1分钟启动一次aria2，防止它崩，结果工具箱全崩了，老板能远程看下么。

**Comment by monlor** [comment]
工具箱全崩了是什么意思

**Comment by lu989898** [comment]
![image](https://user-images.githubusercontent.com/39394489/40265457-38dd471a-5b6b-11e8-8a5f-3f173f48beb0.png)
像是这样

**Comment by monlor** [comment]
有Teamviewer的话，发id密码给我

**Comment by lu989898** [comment]
635067226
1873

**Comment by lu989898** [comment]
我cat了我的下载路径为/userdisk/data/TDDOWNLOAD,
为何他会把/tmp占满？是缓存机制造成的吗？

**Comment by monlor** [comment]
暂时不清楚什么原因造成/tmp不能写入
