### ISSUE TITLE
非常感谢您做这个工具箱，很好用，有几个小建议

### ISSUE THREAD

**Issue by LBBear** [monlor/Monlor-Tools#34]
1。ssr功能缺少“协议参数”这个配置，我买的机场线路只有ssr的用不了
2。可否增加用ss://或ssr://添加节点的功能
3。是否可以考虑增加v2ray，因为相比ssr它不那么吃CPU,小米路由器CPU比较差ssr只能在15M到20M之间

**Comment by LBBear** [comment]
有时无线网会突然消失几秒钟，我只开了ss插件

**Comment by monlor** [comment]
1、ssr有协议参数么？我只知道混淆参数。
2、订阅功能我有时间看看吧。
3、v2ray后续应该会添加
4、无线断线我没遇到过，可能与工具箱无关

**Comment by LBBear** [comment]
加密方法 aes-256-ctr
协议 auth_aes128_md5
协议参数 9285:Amis
混淆方式 tls1.2_ticket_auth
混淆参数HK2SCH1302999e9285.wns.windows.com


我用的就是这种的

Chaco Green <notifications@github.com> 于 2018年5月27日周日 上午1:11写道：

**Comment by monlor** [comment]
测试版已更新，管理菜单里可以更换测试版。

**Comment by LBBear** [comment]
请输入你的选择：1
【Tools】: 正在更新工具箱程序...
【Tools】: 当前版本2.4.29，最新版本2.4.29
【Tools】: 工具箱已经是最新版！

额，没找到测试版啊啊啊

Chaco Green <notifications@github.com> 于 2018年5月27日周日 下午2:32写道：

**Comment by LBBear** [comment]
找到了，谢谢

alice alex <alex0alice@gmail.com> 于 2018年5月27日周日 下午2:35写道：

**Comment by LBBear** [comment]
已更新测试版，没有看到协议参数的配置

**Comment by monlor** [comment]
先更新工具箱，再更新ss插件

**Comment by LBBear** [comment]
已经实验多次，用不了

**Comment by monlor** [comment]
/etc/monlor/apps/shadowsocks/bin/ssr-redir -c /etc/monlor/apps/shadowsocks/config/ss.conf

**Comment by LBBear** [comment]
不好意思额，可能我没表述清楚，有那个协议参数设置了但是线路不通

**Comment by monlor** [comment]
1. web还不完善，等我慢慢更新吧。
2. 最新测试版已经加入了ssr订阅功能
3. v2ray暂时不考虑添加了，先做web

**Comment by LBBear** [comment]
好的呢，ss和ssr订阅功能试了好几个都没解析成功哇，其实感觉v2功能不如ssr暂时不添加也问题，先做web吧，辛苦啦，有打赏通道吗？

**Comment by monlor** [comment]
只支持ssr的订阅，我试了几个订阅都是可以的，你可以试试这个`https://raw.githubusercontent.com/max2max/freess/master/freenode.txt`，账号可能用不了，但是解析出来了。打赏就不用了，本来也是为了学习、方便自己，顺便帮助一下你们。

**Comment by LBBear** [comment]
原来你说的订阅是这种啊，我想直接导入这种ssr://ODkuNDYuMjIzLjE3MTo0NDQ6b3JpZ2luOmFlcy0xMjgtY3RyOnBsYWluOmRHZEhjbTkxY0VOT1IwWlg

**Comment by monlor** [comment]
这个没啥意义啊，你手动输一下就行了。

**Comment by monlor** [comment]
这个里面包含你的ss账号信息，最好删掉。想想可以支持一下，等我更新。

**Comment by LBBear** [comment]
没关系啦，公益节点，没几天会换密码的，问一下你的ss跑fast.com能到多少M啊，我小米路由器3，ss跑18M左右，ssr只有10M左右，以前用斐讯k2p可以跑三十几M

**Comment by monlor** [comment]
k2p的性能优于小米路由器3，快一点很正常。我没有超过10M的ss服务器，无法测试。

**Comment by LBBear** [comment]
哈哈，记错了我以为两个处理器一样，还有个极路由1S处理器和R3一样的刷了老毛子固件同样节点也就14M
