### ISSUE TITLE
 VER:1.7.1     ss插件有点问题

### ISSUE THREAD

**Issue by LBBear** [monlor/Monlor-Tools#35]
添加自定义规则？[1/0]
/etc/rc.common: eval: line 1: Usage:: not found
/etc/rc.common: eval: line 1: del: not found
/etc/rc.common: eval: line 1: show: not found
/etc/rc.common: eval: line 1: clean}: not found
【】: 关闭ss主进程...
【】: 清除iptables规则...
【】: 没有添加ss服务器!
返回主菜单？[1/0]

**Comment by monlor** [comment]
`update.sh -f`，强行更新下工具箱，因为在测试一些东西，没有更新工具箱版本号。

**Comment by LBBear** [comment]
直接url导入的ssr://貌似用不了，可能没解析好

**Comment by monlor** [comment]
cat /etc/monlor/apps/shadowsocks/config/ssserver.conf 你可以你自己对一下，看看节点添加的是否正确。

**Comment by LBBear** [comment]
解析正确，和另一遍手动填的一模一样，并发现手动填的那个也连不上，换回稳定版工具箱同样的节点可以使用

**Comment by monlor** [comment]
测试版更新时ssr有bug，现已解决。
