### ISSUE TITLE
小米路由MINI 的问题

### ISSUE THREAD

**Issue by Aspdian** [monlor/Monlor-Tools#36]
在小米路由MINI 版本中，内部安装，由于内部空间过小，无法完成安装。
当使用外部存储安装，安装成功，不过 SS 无法科学上网。已经测试SS服务器为正常状态。
ROM for Mini 开发版
版本2.17.100（9月29日更新）

**Comment by monlor** [comment]
我测试过mini，应该是没问题的，有报错么？试一下测试版？
