### ISSUE TITLE
R1D安装kod无法启动

### ISSUE THREAD

**Issue by wo20ljj** [monlor/Monlor-Tools#37]
【KodExplorer】: 检测到nginx未配置, 正在配置...
【KodExplorer】: nginx未安装
发现
opt/etc下没有nginx/nginx.conf
没有php.ini

********* KodExplorer ***********
[可道云，在线文档管理器，需要entware环境]
启动kodexplorer服务？[1/0] 1
修改kodexplorer端口号(8080)？[1/0] 1
请输入kodexplorer端口号(默认81)：   
修改kodexplorer管理目录(/userdisk/data)？[1/0] 
【KodExplorer】: 正在停止kodexplorer服务... 
【KodExplorer】: 正在启动kodexplorer服务... 
Unknown package 'php7-cgi'.
Collected errors:
 * opkg_install_cmd: Cannot install package php7-cgi.
Unknown package 'php7-mod-curl'.
Collected errors:
 * opkg_install_cmd: Cannot install package php7-mod-curl.
Unknown package 'php7-mod-gd'.
Collected errors:
 * opkg_install_cmd: Cannot install package php7-mod-gd.
Unknown package 'php7-mod-iconv'.
Collected errors:
 * opkg_install_cmd: Cannot install package php7-mod-iconv.
Unknown package 'php7-mod-json'.
Collected errors:
 * opkg_install_cmd: Cannot install package php7-mod-json.
Unknown package 'php7-mod-mbstring'.
Collected errors:
 * opkg_install_cmd: Cannot install package php7-mod-mbstring.
Unknown package 'php7-mod-opcache'.
Collected errors:
 * opkg_install_cmd: Cannot install package php7-mod-opcache.
Unknown package 'php7-mod-session'.
Collected errors:
 * opkg_install_cmd: Cannot install package php7-mod-session.
Unknown package 'php7-mod-zip'.
Collected errors:
 * opkg_install_cmd: Cannot install package php7-mod-zip.
Unknown package 'nginx'.
Collected errors:
 * opkg_install_cmd: Cannot install package nginx.
Unknown package 'spawn-fcgi'.
Collected errors:
 * opkg_install_cmd: Cannot install package spawn-fcgi.
Unknown package 'zoneinfo-core'.
Collected errors:
 * opkg_install_cmd: Cannot install package zoneinfo-core.
Unknown package 'zoneinfo-asia'.
Collected errors:
 * opkg_install_cmd: Cannot install package zoneinfo-asia.
【KodExplorer】: 检测到nginx未配置, 正在配置...
【KodExplorer】: nginx未安装
返回主菜单？[1/0]

**Comment by monlor** [comment]
entware没有安装成功，不知道你是什么时候安装的entware，工具箱版本号多少。

**Comment by wo20ljj** [comment]
2.4.29

**Comment by wo20ljj** [comment]
entware是提示运行成功了的。然后安装kod就出现这个了。

**Comment by monlor** [comment]
额，我大概知道原因了。安装kod时可能用的系统自带的opkg，等我更新吧。

**Comment by wo20ljj** [comment]
谢谢了。。

**Comment by monlor** [comment]
有一定动手能力，你可以试试测试源，我已经更新了entware。

**Comment by wo20ljj** [comment]
我觉得。应该还是安装lighttpd，更轻巧，适合路由小内存。。请问测试源是啥？

**Comment by wo20ljj** [comment]
好的。。等你更新。。谢谢

**Comment by monlor** [comment]
更新了测试源kodexplorer，你试试吧
