### ISSUE TITLE
未找到插件列表，工具箱异常！

### ISSUE THREAD

**Issue by michealhansun** [monlor/Monlor-Tools#38]
***************************************
   *****  Monlor Tools工具箱  *****
***************************************
当前版本：[2.6.10]	最新版本：[2.6.10]
设备型号：[R3]  	上网方式：[pppoe]
***************************************
[未找到插件列表，工具箱异常！]
root@XiaoQiang:~# update.sh -f
【Tools】: 正在更新工具箱程序... 
【Tools】: 解压工具箱文件
【Tools】: 更新工具箱配置脚本
【Tools】: 更新工具箱文件
【Tools】: 赋予可执行权限
cat: can't open '/etc/monlor/config/applist.txt': No such file or directory
【Tools】: 工具箱更新完成！
1. 工具箱新增web界面，暂时只有ss和kp两个插件，支持最新版固件
2. 压缩了大多数插件的二进制文件，减少磁盘占用
3. ss插件新增订阅节点功能
root@XiaoQiang:~#

**Comment by monlor** [comment]
别这么更新，我尝试修复了一下。更新工具箱运行monlor，输入u更新。

**Comment by monlor** [comment]
额，，，新版我改进了下这个问题。`update.sh -f` 只能这么更新了

**Comment by monlor** [comment]
现在运行monlor，如果找不到插件列表，会自动修复。

**Comment by michealhansun** [comment]
ok，可以了，谢谢

**Comment by InfinityGuo** [comment]
当前版本：[2.6.10]	最新版本：[2.6.10.1]
设备型号：[R3] 上网方式：[pppoe]
-----------------------------------------------------------------------------------------------
R3的工具箱版本已经更新到2.6.10了吗？我的是R3G，看了下最新版本还是2.4.29 。

**Comment by monlor** [comment]
测试版是2.6.10，正式版2.4.29，我只是懒得更新正式版了😂。

**Comment by InfinityGuo** [comment]
请教一下如何装测试版啊？
小白一枚，看readme文档一键安装的。

**Comment by monlor** [comment]
管理菜单里更换测试源就行了。

**Comment by InfinityGuo** [comment]
嗯，更换测试源后，重新访问工具箱，提示输入u，成功更新版本。
那么，web管理台的地址是？😂

**Comment by monlor** [comment]
web是嵌入在小米路由器管理页面的，类似Misstar Tools。
