### ISSUE TITLE
能否增加SS的DNS加强功能？

### ISSUE THREAD

**Issue by InfinityGuo** [monlor/Monlor-Tools#39]
由于Misstar Tools里的SSR不能设置混淆参数，搜寻后发现了Monlor工具箱。

但是我家里的Google Home Mini，**在单独开启Monlor工具箱的SS服务时，无法连上网**。我自己的解决方法是开启Monlor SS服务+开启Misstar Tools里的SS（不添加节点，只开启里面的DNS加强功能，选择DNS2SOCKS模式）。这样操作后能短暂使Google Home Mini翻出去，但是每天早上依然会断网，解决方法是刷新一下Misstar Tools里的SS工具状态（重新提交一次DNS加强）。

能否将Misstar Tools SS里面的DNS加强功能搬到Monlor工具箱中？这样就能完全代替Misstar Tools，做到支持SSR混淆参数+稳定性+一站式设置便利性。

非常感谢作者，Monlor Tools是个好用省心的工具，希望一直更新下去。

**Comment by monlor** [comment]
Monlor Tools是自带dns2socks的。

**Comment by InfinityGuo** [comment]
嗯，看到了在启动SS服务时有启动dns2socks，但不知道为啥我这Google Home mini 就是连不上网。我再试试看吧~跟上级DNS 设置8.8.8.8这个有关吗？因为看到Misstar Tools里有这个。

**Comment by monlor** [comment]
我懂了，应该是上级dns固定为8.8.8.8了，我更新一下dns重定向吧。

**Comment by InfinityGuo** [comment]
看到小米路由器后台里的插件中心了，替代掉了Misstar Tools的位置。👍
又试了一下，开启全局模式，Google Home Mini能正常上网。黑名单模式则不行。

**Comment by InfinityGuo** [comment]
虽然不太明白原理，但是感觉有望解决。
非常感谢！

**Comment by InfinityGuo** [comment]
补充：白名单模式也能连接上。只有黑名单模式不可以。

**Comment by monlor** [comment]
我更新了dns重定向功能，你试试。

**Comment by InfinityGuo** [comment]
修改DNS配置(重定向, 8.8.8.8, 53)？[1/0] 1
启用DNS重定向？[1/0] 1
修改DNS重定向IP地址(192.168.31.1)： **直接回车**
输入代理使用DNS服务器(8.8.8.8)： **直接回车**
输入代理使用DNS端口号(53)： **直接回车**

按以上设置后，Google Home Mini在黑名单模式下也能正常联网。完美解决！👍

能否科普下以上设置解决问题的原理？😊

**Comment by monlor** [comment]
因为google home可能跟chromecast类似，使用8.8.8.8的DNS，无法翻墙。在路由器上把局域网所有设备的DNS强制重定向给路由器来解析，这样就行了。

**Comment by InfinityGuo** [comment]
嗯，明白了~ (๑•̀ㅂ•́)و✧  已经用Monlor彻底替代了Misstar Tools
