### ISSUE TITLE
无法更新测试源

### ISSUE THREAD

**Issue by laozhu999** [monlor/Monlor-Tools#40]
本人是个爱折腾的小白，misstar已经折腾到半死了，虽然成功了，但是ss版本太老了。发现了你这个好东西，看到有web的供小白用，就试了。结果如下：

请输入你的选择：09
1. coding下载源
2. github下载源
3. coding测试源(不建议)
请选择下载源：3
/etc/monlor/scripts/monlor: line 333: /etc/monlor/scripts/getver.sh: not found
返回主菜单？[1/0] ^C
root@XiaoQiang:~# 
这下就真小白了，难道是要先装几个插件不成？

**Comment by monlor** [comment]
运行update.sh -f

**Comment by monlor** [comment]
curl -sL `uci get monlor.tools.url`/scripts/update.sh | sh

**Comment by monlor** [comment]
curl -sL $(uci get monlor.tools.url)/scripts/update.sh | sh

**Comment by laozhu999** [comment]
我的神啊， 好了，但是菜单里只有ss
获取工具箱版本信息...
***************************************
   *****  Monlor Tools工具箱  *****
***************************************
当前版本：[2.6.11]	最新版本：[2.6.11]
设备型号：[R3G]  	上网方式：[dhcp]
***************************************
00. 管理菜单(Ctrl + c退出)
01. shadowsocks	[未运行] 

请输入你的选择：

**Comment by monlor** [comment]
管理菜单里安装插件就行了。

**Comment by laozhu999** [comment]
koolproxy 选项有点多啊。。

**Comment by laozhu999** [comment]
ss可以web设定吗，还是要去管理菜单啊？

**Comment by monlor** [comment]
ss的web功能暂时不全

**Comment by laozhu999** [comment]
嗯嗯，会好起来的！ss有gwlst模式吗，黑白名单有点难搞啊？

**Comment by monlor** [comment]
有gfwlist模式

**Comment by laozhu999** [comment]
菜单来开关和设置，web来管理。明白了。

**Comment by laozhu999** [comment]
好像没有看到gfwlist模式？

**Comment by LBBear** [comment]
黑名单就是
