### ISSUE TITLE
麻烦您能说一下aria2插了移动硬盘之后怎么设置吗

### ISSUE THREAD

**Issue by LBBear** [monlor/Monlor-Tools#41]
不太会用

**Comment by LBBear** [comment]
下载路径怎么设置呢

**Comment by monlor** [comment]
你可以看看你硬盘的路径，`df -h`，然后在aria2设置菜单里添加相应的地址即可。

**Comment by LBBear** [comment]
磁力可以添加但不下载，http放进去之后直接未知错误

**Comment by monlor** [comment]
你下载路径怎么设置的？

**Comment by LBBear** [comment]
我查到是这个
/dev/sda1                 1.8T   1022.3G    840.7G  55% /extdisks/sda1

先设置成/dev/sda1结果报错，所以设置为/extdisks/sda1没有报错，但是不能下载

**Comment by monlor** [comment]
所有链接都不能下载？

**Comment by LBBear** [comment]
活的电脑bt客户端能下载的磁力链不动，http的下载链接就直接显示未知错误

**Comment by LBBear** [comment]
找到原因了，BT设置里没有添加bt服务器地址，添加后有速度，但是一旦Aria2重启或者路由器重启后，原先添加的就不见了

**Comment by LBBear** [comment]
有时不重启也会消失

**Comment by monlor** [comment]
你在webui里添加的？没修改工具箱的aria2配置么

**Comment by LBBear** [comment]
是的，不会用命令啊

Chaco Green <notifications@github.com> 于 2018年7月6日周五 19:21写道：

**Comment by monlor** [comment]
你可以winscp连接路由器，编辑/etc/monlor/apps/aria2/config/aria2.conf这个文件
