### ISSUE TITLE
科学上网问题

### ISSUE THREAD

**Issue by iceyheart** [monlor/Monlor-Tools#42]
您好！非常感谢能用到您开发的monlor工具箱！我在使用中碰上ssr插件的问题：
1、	能否变更本地端口？默认为1081，但我的服务器要求1080
2、	缺少协议参数protocol_param选项
目前使用下，虽然工具箱已显示连接，但无法实际连网
请不吝指教，谢谢！

**Comment by monlor** [comment]
1. 服务器还强制要求ss运行在1080端口？
2. 测试版有协议参数选项的
3. 你配置不对当然连不上

**Comment by monlor** [comment]
更换测试版方法，运行monlor管理菜单更换测试源，返回主菜单输入u即可。

**Comment by monlor** [comment]
另外，1080端口已经被迅雷占用了。

**Comment by iceyheart** [comment]
非常感谢。已经可以使用了！有个小BUG是升级后菜单数字对不上。。要大一位输入才能选中

**Comment by monlor** [comment]
`rm -rf /etc/monlor/config/applist.txt`，重新运行monlor会自动获取插件列表。

**Comment by iceyheart** [comment]
非常感谢，解决了问题！
顺便请教下，用了SS后还有必要开IPV6服务吗？
我用迅雷下载或bt、aria等，会不会走到ss流量去？（使用GFW列表）

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Chaco Green <notifications@github.com>
发送时间: Saturday, June 16, 2018 4:08:07 PM
收件人: monlor/Monlor-Tools
抄送: iceyheart; Author
主题: Re: [monlor/Monlor-Tools] 科学上网问题 (#42)


rm -rf /etc/monlor/config/applist.txt，重新运行monlor会自动获取插件列表。

―

**Comment by monlor** [comment]
不用开ipv6服务，如果你下载GFW内的资源肯定会消耗流量的。

**Comment by iceyheart** [comment]
请教，R2D上能部署plex media server吗？

发自我的 iPhone

在 2018年6月16日，17:31，Chaco Green <notifications@github.com<mailto:notifications@github.com>> 写道：


不用开ipv6服务，如果你下载GFW内的资源肯定会消耗流量的。

**Comment by monlor** [comment]
这个东西不考虑，太耗系统资源了。
