### ISSUE TITLE
小米路由mini frp启动不起立？

### ISSUE THREAD

**Issue by wanababy** [monlor/Monlor-Tools#45]
试了好多次，偶尔能启动，再试就不行了

**Comment by monlor** [comment]
可能是配置问题，请查看日志`cat /var/log/frp*`

**Comment by wanababy** [comment]
还是启动不起来，配置和我在别的地方一样。
现在这个frp版本是最新的吗？
看配置文件不像最新的，能不能更新下？
log里面什么都没有。

**Comment by monlor** [comment]
嗯，frp版本挺多不兼容，工具箱里是0.16的，我考虑加个版本选择

**Comment by monlor** [comment]
嗯，frp版本挺多不兼容，工具箱里是0.16的，我考虑加个版本选择

**Comment by wanababy** [comment]
好吧，尽量保持最新的，威力也要更新了，打开页面就提示，谢谢！
还有好像firewall插件不大管用，我改了系统的才能用。

**Comment by monlor** [comment]
verysync是自动更新的，firewall仅仅开放端口，对小米的web页面可能无效。

**Comment by up76733** [comment]
你好，我的也是启动不起来。
不理解配置过程中的「请输入frpc的user配置：」  这里面的user配置是指frps.ini 或frps_full.ini 中的哪一项？

服务器配置：
`# [common] is integral section
[common]
# A literal address or host name for IPv6 must be enclosed
# in square brackets, as in "[::1]:80", "[ipv6-host]:http" or "[ipv6-host%zone]:80"
bind_addr = 0.0.0.0
bind_port = 7000
# udp port used for kcp protocol, it can be same with 'bind_port'
# if not set, kcp is disabled in frps
kcp_bind_port = 7000
# if you want to configure or reload frps by dashboard, dashboard_port must be set
dashboard_port = 7500
# dashboard assets directory(only for debug mode)
dashboard_user = admin
dashboard_pwd = ****
# assets_dir = ./static
vhost_http_port = 8081
vhost_https_port = 8082
# console or real logFile path like ./frps.log
log_file = ./frps.log
# debug, info, warn, error
log_level = info
log_max_days = 3
# auth token
token = *****
# only allow frpc to bind ports you list, if you set nothing, there won't be any limit
#allow_ports = 1-65535
# pool_count in each proxy will change to max_pool_count if they exceed the maximum value
max_pool_count = 50
# if tcp stream multiplexing is used, default is true
tcp_mux = true`


启动过程
`[内网穿透工具，相对于ngrok资源占用较多]
启动frpc服务？[1/0] 1
1.[0.9.3] 2.[0.17.0] 3.[0.20.0]
请选择frpc运行版本(回车不修改，默认最新)：3
修改frpc服务器($ip, 7000, twfrp)？[1/0] 1
请输入frpc服务器：$ip
请输入frpc服务器端口：7000
请输入frpc服务器秘钥：$token
请输入frpc的tcp_mux配置(true/false)：true
请输入frpc的user配置：admin
请输入frpc的协议配置protocol：tcp
frpc穿透配置[shell]
添加frpc穿透配置？[1/0] 0
删除frpc穿透配置？[1/0] 0
【Frpc】: 正在停止frpc服务...
【Frpc】: 正在启动frpc服务...
【Frpc】: 生成frpc配置文件
【Frpc】: 加载frpc配置:【shell】启动为http/https自定义域名模式,域名:[shell.dalh.top]
【Frpc】: 启动frpc服务完成！
返回主菜单？[1/0] 1`



本地log：
`2018/07/22 16:41:45 [I] [proxy_manager.go:300] proxy removed: []
2018/07/22 16:41:45 [I] [proxy_manager.go:310] proxy added: []
2018/07/22 16:41:45 [I] [proxy_manager.go:333] visitor removed: []
2018/07/22 16:41:45 [I] [proxy_manager.go:342] visitor added: []
2018/07/22 16:41:46 [I] [control.go:246] [6f868e19fd1245df] login to server success, get run id [6f868e19fd1245df], server udp port [0]
2018/07/22 16:42:37 [I] [proxy_manager.go:300] proxy removed: []
2018/07/22 16:42:37 [I] [proxy_manager.go:310] proxy added: []
2018/07/22 16:42:37 [I] [proxy_manager.go:333] visitor removed: []
2018/07/22 16:42:37 [I] [proxy_manager.go:342] visitor added: []
2018/07/22 16:42:38 [I] [control.go:246] [f4e3b3aaa4ce5228] login to server success, get run id [f4e3b3aaa4ce5228], server udp port [0]`

**Comment by up76733** [comment]
我自己下载frp之后手动配置是可以连接正常的，应该是0.20.0的配置上的问题

只要配置好服务器、端口、token就可以了

[common]
server_addr = 服务器ip
server_port = 7000
token = ****


[files]                
type = http            
local_ip = 192.168.31.1        
local_port = 1086              
custom_domains = 我的域名


root@XiaoQiang:/etc/frpc/frp_0.20.0_linux_mipsle# ./frpc -c ./frpc.ini            
2018/07/25 16:02:21 [I] [proxy_manager.go:300] proxy removed: []
2018/07/25 16:02:21 [I] [proxy_manager.go:310] proxy added: [files]
2018/07/25 16:02:21 [I] [proxy_manager.go:333] visitor removed: []
2018/07/25 16:02:21 [I] [proxy_manager.go:342] visitor added: []
2018/07/25 16:02:23 [I] [control.go:246] [10b631c3a9a8219a] login to server succes
s, get run id [10b631c3a9a8219a], server udp port [0]                             
2018/07/25 16:02:24 [I] [control.go:169] [10b631c3a9a8219a] [files] start proxy su
ccess

**Comment by monlor** [comment]
user配置随便输就行了，相当于一个用户名。协议尝试一下kcp，因为你服务端是启用了kcp的。
