### ISSUE TITLE
感谢大神，关于 SS 插件还有几个问题

### ISSUE THREAD

**Issue by itspig** [monlor/Monlor-Tools#48]
1. 白名单，黑名单，全局模式支持 UDP 协议吗？
2. 游戏模式是指支持 UDP 吗，海外游戏模式 和 国内游戏模式 是指部分游戏的网址走 SS 吗？
3. 能否添加一个 GEOIP 的模式，CN 外 IP 的都翻墙，我觉得这样就不用写自定义规则了？
4. 有空可否支持下 SS 原版混淆？（您如果觉得麻烦就忽略吧）
5. WEB 界面后续会添加局域网控制等高级设置选项吗，命令行还是操作不便啊！

多谢！！！

**Comment by monlor** [comment]
1. 都不支持。
2. 因为小米路由器本身原因，UDP仅支持部分路由器，支持R1D、R2D。
3. CN外的IP都翻墙？就是大陆白名单模式吧。
4. ss原版混淆添加可以考虑添加。
5. 后续命令行的功能都会添加到web界面的。
