### ISSUE TITLE
R1CM更新完之后Permission denied

### ISSUE THREAD

**Issue by mezhangyes** [monlor/Monlor-Tools#49]
-ash: monlor: Permission denied

**Comment by monlor** [comment]
运行更新命令再更新一遍呢，update.sh -f

**Comment by mezhangyes** [comment]
我重装一遍之后直接-ash: monlor: not found

**Comment by mezhangyes** [comment]
我试下重置下路由

**Comment by mezhangyes** [comment]
还是not found 有没有以前的版本。。

**Comment by mezhangyes** [comment]
现在是安装不上了

**Comment by monlor** [comment]
安装完重新登陆下ssh呢

**Comment by mezhangyes** [comment]
touch: /etc/config/monlor: No space left on device
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
cp: can't stat '/etc/monlor/config/monlor.uci': No such file or directory
uci: Entry not found
uci: Entry not found
uci: Entry not found
【Tools】: 添加工具箱Web页面
/extdisks/sda1/.monlor/scripts/init.sh: line 49: /scripts/addweb: not found
【Tools】: 检查环境变量配置
ash: write error: No space left on device
【Tools】: 检查定时任务配置
sed: can't create temp file '/etc/crontabs/rootLHyq53': No space left on device
uci: Entry not found
【Tools】: 检查工具箱开机启动配置
/extdisks/sda1/.monlor/scripts/init.sh: line 64: can't create /etc/firewall.user: No space left on device
【Tools】: 运行工具箱监控脚本
/extdisks/sda1/.monlor/scripts/init.sh: line 77: /scripts/monitor.sh: not found
sed: can't create temp file '/etc/crontabs/rootucFdO4': No space left on device
ash: write error: No space left on device
【Tools】: 运行用户自定义脚本
/extdisks/sda1/.monlor/scripts/init.sh: line 137: /scripts/userscript.sh: not found
【Tools】: 工具箱安装完成!
【Tools】: 运行monlor命令即可配置工具箱
root@XiaoQiang:~#

**Comment by mezhangyes** [comment]
我装在外置存储也没用

**Comment by monlor** [comment]
这个空间不足没办法，你可以尝试一下旧版固件，空间多一点，

**Comment by monlor** [comment]
你可以加我qq，有时间我远程帮你看看吧，421599756

**Comment by mezhangyes** [comment]
我刷回去2.17.100版了 能装上了

**Comment by mezhangyes** [comment]
现在只能装在外置存储了

**Comment by monlor** [comment]
R1CM不能安装在内置储存

**Comment by mezhangyes** [comment]
我发现有bug诶 = = 
我明明关了ss 过了一会他又自动开了

**Comment by monlor** [comment]
有没有安装别的什么插件？先勉强用着吧，工具箱暂时停更。

**Comment by mezhangyes** [comment]
= =停止下载了吗

**Comment by WarlockFish** [comment]
请问你还有包吗，我刷了最新的固件说是磁盘不足，能发我一份过去的固件吗？   邮箱941510759@qq.com
