### ISSUE TITLE
更新6月24日版本后ngrok：Command failed: Not found

### ISSUE THREAD

**Issue by rlad2333** [monlor/Monlor-Tools#50]
路由器：小米路由PRO R1D
服务端：用Win客户端测试无问题
之前版本的ngrok无问题，更新6.24版本后出现：

> ngrok穿透配置[空]
> 添加ngrok穿透配置？[1/0] 1
> 请输入ngrok名称：QB
> 请输入ngrok类型(1.http 2.tcp)：1
> 请输入ngrok本地ip(回车默认192.168.31.1)：192.168.1.141
> 请输入ngrok本地端口：8080
> 请输入ngrok域名(自动识别子域名或自定义域名)：qb
> 确定要添加配置：QB,http,192.168.1.141,8080,,qb？[1/0] 1
> 添加完成，再添加一个？[1/0] 0
> 删除ngrok穿透配置？[1/0] 0
> Command failed: Not found
> 【Ngrok】: 正在停止ngrok服务...
> 【Ngrok】: 正在启动ngrok服务...
> 【Ngrok】: 启动ngrok服务完成！
> 返回主菜单？[1/0]

服务显示启动，但远程连接失败 ..

**Comment by rlad2333** [comment]
root@XiaoQiang:/tmp/log# cat ngrok.log
ok

**Comment by monlor** [comment]
直接重启ngrok看看，`/etc/monlor/apps/ngrok/script/ngrok.sh restart`

**Comment by rlad2333** [comment]
> root@XiaoQiang:/# /etc/monlor/apps/ngrok/script/ngrok.sh restart
> Command failed: Not found
> 【Ngrok】: 正在停止ngrok服务...
> 【Ngrok】: 正在启动ngrok服务...
> 【Ngrok】: 启动ngrok服务完成！
> root@XiaoQiang:/#

**Comment by rlad2333** [comment]
服务显示是运行OK 的，但实际不能使用。

**Comment by rlad2333** [comment]
大哥！好使了！
虽然还是 Command failed: Not found。

**Comment by monlor** [comment]
这里有一个报错，`Command failed`，不清楚是什么报错。

**Comment by monlor** [comment]
因为我也没有R1D测试设备。

**Comment by monlor** [comment]
这个错误可能是没运行成功导致的，你多重启几次就行了。

**Comment by rlad2333** [comment]
非常感谢！
^^
