### ISSUE TITLE
3G的路由器Aria2死机

### ISSUE THREAD

**Issue by Murphy-Chung** [monlor/Monlor-Tools#51]
作者，你的工具箱里面的Aria2有在3G的环境下测试过吗？我试了一下下载BT任务会直接把路由器卡死。
还有作者打算什么时候完善web端？

**Comment by monlor** [comment]
没有测试环境，只保证R2D运行正常。暂时停更。

**Comment by iceyheart** [comment]
版主您好。我的是R2D，今晚试了下aria2，下载一会儿路由器就卡死了，是哪设置有问题吗
[aria2.conf.txt](https://github.com/monlor/Monlor-Tools/files/2163664/aria2.conf.txt)

**Comment by iceyheart** [comment]
出现过的情况下，ariaNG上还能看到在下载，但是通过SSH进工具箱显示的是aria2未运行。同时SSR也被关闭了，再次开启报错显示no enough space 。后面几次的情况就是直接都无法连接路由器了。

**Comment by iceyheart** [comment]
ash写入错误。没有足够空间

**Comment by monlor** [comment]
aria2地址设置可能有问题，硬盘地址为/userdisk/data

**Comment by iceyheart** [comment]
地址为默认。/userdisk/data/下载

**Comment by iceyheart** [comment]
我想可能是CPU占用过高的问题。才2M的下载速度，CPU占用就达到100%，然后系统就会崩溃、重启等。能否加上cpulimit等软件来限制CPU使用率呢

**Comment by Murphy-Chung** [comment]
我在3G上观察到的情况是使用Aria2的时候，内存占用过大，应该和硬件性能优化不足有关。@iceyheart@monlor

**Comment by monlor** [comment]
这个问题我尝试给3G换一个aria2程序吧
