### ISSUE TITLE
麻烦可以出一些小白教程吗

### ISSUE THREAD

**Issue by minor8429** [monlor/Monlor-Tools#52]
首先很感谢作者，路由之前刷过潘多拉，但由于某些原因，又刷回了官方，官方插件真的少的可怜，感谢你的付出，让官方固件也有了折腾的可能。
由于完全技术小白，所有东西都是靠百度或者论坛，但有时想百度也百度不了，例如昨天安装了VsFtpd，能启动，可是目录一直为空，路径也没错。越到这些问题时，就很希望每个插件都有个简单教程，跟着做，就应该不会错了，错了也可以和其他人讨论交流一下。

**Comment by monlor** [comment]
用的人不多，也没有精力再去完善教程了，只能希望用过的人来完善一下教程。

**Comment by minor8429** [comment]
好的，假如遇到技术问题再请教请教，谢谢你的付出。
