### ISSUE TITLE
球一个GFW列表更新功能

### ISSUE THREAD

**Issue by LBBear** [monlor/Monlor-Tools#53]
目前不可以用黑名单模式访问telegram

**Comment by monlor** [comment]
gfwlist会自动更新，但是里面没有telegram的地址，你可以手动添加黑名单规则

**Comment by LBBear** [comment]
我搜到了ip但是不太会添加
109.239.140.0/24
149.154.160.0/20
149.154.164.0/22
149.154.168.0/22
149.154.172.0/22
91.108.4.0/22
91.108.56.0/22
91.108.8.0/22
添加黑名单的时候把这些一次全部粘贴进去之后就不能回车了，而且会跳exit什么的

**Comment by monlor** [comment]
但是不支持ip😂
