### ISSUE TITLE
请问一下，我SS用订阅地址 和ssr的地址都是失败

### ISSUE THREAD

**Issue by flashcg** [monlor/Monlor-Tools#54]
SS有节点的存储文件吗，在什么位置呢，我想编辑一下,命令行窗口导入太累了

**Comment by monlor** [comment]
ss不支持订阅，只支持ssr。/etc/monlor/apps/shadowsocks/config/ssserver.conf

**Comment by tea1111980** [comment]
#71 你可以试一下这个帖中的内容
