### ISSUE TITLE
求添加新功能

### ISSUE THREAD

**Issue by 8ylYile** [monlor/Monlor-Tools#55]
在misstar上有几个功能
VPN服务器 用于在小米路由器上架设VPN的，AliDDNS 阿里云DDNS ，远程访问，这个功能是给那些路由器PPPOE连接且为外网IP的玩家用的，web外部访问端口添加的。
求大佬添加下，谢了，如果你有赞助的话，我想赞助您一些维护开发的辛苦费。

**Comment by monlor** [comment]
关闭工具箱的webui可以跟misstar tools共存，web外部访问小米社区有教程（可以考虑添加），其他的暂时不考虑。

**Comment by 8ylYile** [comment]
不是，我这个miwifi新版固件没办法解决misstar-tools显示。。。求在您的工具箱内添加修复misstar的功能

**Comment by monlor** [comment]
这个问题，misstar作者即将更新新版工具箱。

**Comment by monlor** [comment]
这个具体我也不清楚，可以关注misstar tools的qq群

**Comment by 8ylYile** [comment]
可是我没加入 因为要钱 你那边能套到MT3.0的消息吗？
