### ISSUE TITLE
同学，我发现一个BUG

### ISSUE THREAD

**Issue by DanLanEX** [monlor/Monlor-Tools#58]
如果KoolProxy在运行的话，不知什么原因，除了22端口，所有端口都会暴露给外网。原因未知。

**Comment by DanLanEX** [comment]
这是截图

https://www.icloud.com/iclouddrive/09SLI7DtpRW0onvBv5WYFHSyQ#%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7_2018-07-22_%E4%B8%8A%E5%8D%888.04.12.png

https://www.icloud.com/iclouddrive/0wXl6Dm1u3zc39eLVbTtrmNtw#%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7_2018-07-22_%E4%B8%8A%E5%8D%888.05.09.png

**Comment by monlor** [comment]
不会啊，工具箱的koolproxy并没有开通端口的相关命令

**Comment by DanLanEX** [comment]
你KoolProxy用全局模式，试一下

**Comment by monlor** [comment]
主要是我没有公网IP，也没有上级路由的环境，无法测试。

**Comment by DanLanEX** [comment]
好吧，我换了黑名单模式就不会这样了，但是全局模式100%复现。
