### ISSUE TITLE
SS下载订阅节点地址失败、连接时提示“未找到SS节点”

### ISSUE THREAD

**Issue by NigelSong** [monlor/Monlor-Tools#59]
第一个问题，在“添加SS节点”时，选择“订阅地址”，提示“下载订阅节点失败”（订阅网址本身未被墙，手机和电脑都可以正常更新）。图片：https://s7d1.turboimg.net/sp/1dbc6b41d19544c7b0187fb7fd46d9b2/Screenshot_20180723-234033__01.jpg
第二个问题（已解决），手动配置节点信息，创建配置文件时却提醒“未找到SS节点，请重试”。图片：https://s7d1.turboimg.net/sp/8d083a1fc4e47444fb036de094d8c20f/Screenshot_20180723-233811__01.jpg

**Comment by NigelSong** [comment]
好的，我的QQ号是1978712298，请确认

**Comment by NigelSong** [comment]
问题已解决。需要自定义一个第三方的curl，系统自带的curl对https不友好。

**Comment by tea1111980** [comment]
@NigelSong 你说的这个代理节点的问题，可以参考我的 #71
