### ISSUE TITLE
cannot download ngrok

### ISSUE THREAD

**Issue by farhanito** [monlor/Monlor-Tools#6]
tried to install ngrok, but failed..

请输入你的选择(exit退出)：7

确定要安装ngrok插件？[1/0] 1
【Tools】: 正在安装【ngrok】在线插件...
【Tools】: 下载程序中...
【Tools】: 校验MD5文件信息
【Tools】: 下载【ngrok】文件失败！
返回主菜单？[1/0]

**Comment by monlor** [comment]
where are you from? not China?

**Comment by farhanito** [comment]
no, i'm not.. is that a problem?

**Comment by monlor** [comment]
maybe ,you can change the download url. I updated Tools just now.
now, you can run this command:
`
update.sh -f
monlor
`
run monlor , select 0, select 9, select 2

![default](https://user-images.githubusercontent.com/20394007/34771974-6404c77c-f641-11e7-85f3-75aff7f01f54.PNG)

**Comment by monlor** [comment]
display with problem, 1. update.sh -f     2. monlor

**Comment by farhanito** [comment]
sorry.. noob question. 
where can i get ngrok server, port, and key? 
can you please give some usage examples? 

thanks in advance

**Comment by monlor** [comment]
ok, you can try `https://ngrok.cc/` or `http://www.ittun.com/`
