### ISSUE TITLE
请问里面的签到插件怎么用？

### ISSUE THREAD

**Issue by tea1111980** [monlor/Monlor-Tools#62]
qiandao 这个插件怎么使用？ 在配置的时候它要求输入要签到网站的Cookies 这东西哪里去弄?

![image](https://user-images.githubusercontent.com/16295097/43362496-e2cce0e8-931d-11e8-8537-495cbbe4f567.png)

![image](https://user-images.githubusercontent.com/16295097/43362498-eb7d182a-931d-11e8-8472-7a1dd17be8bb.png)

百度的Cookies 是不是取 BDUSS 这个字段里的内容啊？
大概的过程就是这样。

**Comment by monlor** [comment]
百度我试的貌似不行，你可以关了百度签到试试别的网站行不行。

**Comment by tea1111980** [comment]
好的，问一下，你有 Telegram or Discord ?

**Comment by monlor** [comment]
telegram有，因为没什么群和好友，不经常用。

**Comment by tea1111980** [comment]
哦，那就TG吧，方便随时反馈。

**Comment by tea1111980** [comment]
老大，你没加我啊。 TG

**Comment by tea1111980** [comment]
koolproxy 无法过滤优酷广告，爱奇艺可过滤，其它的网站没有试。
优酷广告过滤咋弄？

**Comment by tea1111980** [comment]
我手机上的优酷过滤是好的，就是电脑上面不能。

**Comment by tea1111980** [comment]
你没有QQ群吗？我感觉建一个会好一些的。
