### ISSUE TITLE
R1D SS自定义规则不生效

### ISSUE THREAD

**Issue by cloudtuotuo** [monlor/Monlor-Tools#65]
R1D ROM：2.25.xxx开发版
Monlor：2.6.24

现象：
安装SS后，SS可以连通节点
启用黑名单或白名单模式，将ip.cn增加到自定义黑名单或是白名单，ip.cn均无法显示节点IP
添加进自定义名单是通过Monlor管理界面添加的，查看conf文件可以看到ip.cn在文件内

是否在添加自定义名单时，不是仅输入“ip.cn”？
或是其他什么原因，还望指教

**Comment by cloudtuotuo** [comment]
root@XiaoQiang:/etc/monlor/apps/shadowsocks/config# cat customize_black.conf                                                   
ip.cn
root@XiaoQiang:/etc/monlor/apps/shadowsocks/config# cat customize_white.conf                                                   
root@XiaoQiang:/etc/monlor/apps/shadowsocks/config# 

尝试从黑名单切换至白名单，不行；切换至全局，可以；切换回黑名单，不行

**Comment by tea1111980** [comment]
你想查看正在使用的代理IP 是吧？  装一个可以分流的插件就行了，如果你用Chrome浏览器的话。

比如这个：[https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif](url)

如果是其它浏览器，只能使用全局模式后，才能在ip.cn查看到使用哪个代理的IP了
