### ISSUE TITLE
关于几个异常和建议

### ISSUE THREAD

**Issue by YongJie-Xie** [monlor/Monlor-Tools#67]
路由器：R2D-开发版-2.23.160
1、在工具箱修改hosts后路由器的DNS直接全部挂掉
至于为什么，我也不清楚
2、签到插件抛异常（绝对路径的问题，不明觉厉）
【QianDao】: 出错了，1秒后尝试重新启动...
-------------------------------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x281004]

goroutine 1 [running]:
github.com/headzoo/surf/browser.(*Browser).Body(0x109fe280, 0x32427c, 0x4a)
	D:/GO/src/github.com/headzoo/surf/browser/browser.go:612 +0x1c
GO/qiandaodog/tieba.Tieba(0x10904500, 0x261)
	D:/GO/src/GO/qiandaodog/tieba/tieba.go:17 +0x98
main.main()
	D:/GO/src/GO/qiandaodog/main.go:50 +0x8e8
3、WebShell这个功能手机不能正常使用
不能打字输入
4、ss的白名单模式好像其实就是GFWList模式吧，建议直接改回这个名字吧，好认～

**Comment by YongJie-Xie** [comment]
好的，原来我一直用错了，webshell我去反馈一下吧，谢谢大佬～

**Comment by tea1111980** [comment]
@YongJie-Xie  大兄弟啊，你跟我遇到的问题一样，百度签到的问题。最后你找到解决办法了没有?

**Comment by tea1111980** [comment]
@YongJie-Xie  这个问题我解决了，需要安装go语言程序

**Comment by YongJie-Xie** [comment]
@tea1111980 我试过了，解决方案有效，你真棒~

**Comment by tea1111980** [comment]
@YongJie-Xie  吓屎我了，我还以为没用呢。

还有，那个签到插件到底怎么用，你能教教我吗？我签百度的时候老是提示打开网站失败。

**Comment by tea1111980** [comment]
@monlor  我跟作者反馈了，看他的issues里面的提问者问的问题，都是2017年的东西，而且他没有回复我。
今天SSR出现问题了，自己突然提示链接异常，并且所有的网页都打不开，QQ没事。
后来我卸载重装了一遍还是没好，再后来我又重装一遍并且重启了路由就好了。
哎~~真是怪。

**Comment by monlor** [comment]
签到作者不知道咋了……可能很忙。这种概率性事件无法捕捉，没啥办法。而且按理说是要么就用不了，突然用不了我只遇到过账号有问题才这样。
