### ISSUE TITLE
R3P 的applist里面没有Entware，是因为架构不支持吗？

### ISSUE THREAD

**Issue by wanguolin** [monlor/Monlor-Tools#68]
从脚本中找到/tmp的applist位置，发现没有Entware，但是在Entware的release中看到armv5 v7和mips，不知道是何种考虑导致applist中没有列出Entware？

Readme中列出支持，所以想起来安装一下试试，今儿发现无法从ssh命令行中安装。

**Comment by monlor** [comment]
你可以试一下，因为我测试r3用不了，其他mips路由器我无法测试，所以就移除了mips的entware。运行`appmanage.sh add entware` 可以尝试安装。

**Comment by monlor** [comment]
可以使用命令ldd查看一下缺少哪些依赖，试着用opkg装一下。

**Comment by wanguolin** [comment]
是opkg本身file not found，我参考了这篇文章http://bbs.xiaomi.cn/t-15153456，再启动monlor的时候，entware就显示一切正常了。对了，你知道小米路由如何mount samba共享吗，我尝试mount nas的SMB来做下载盘，但是总是显示没有这个设备，我试过mount -t cifs 和 mount -t samba，都不行。用opkg尝试安装cifs-utils，似乎也不行。
