### ISSUE TITLE
这是什么问题？

### ISSUE THREAD

**Issue by tea1111980** [monlor/Monlor-Tools#69]
![image](https://user-images.githubusercontent.com/16295097/44245392-052d6080-a20b-11e8-86b8-e50f83baceac.png)

我的小米路由昨天刚刚更新的固件，然后monlor没有了，我重装了，再然后装koolproxy的过程中，如上图所示。
请问这个对于这个程序有影响吗？

**Comment by monlor** [comment]
可能需要你的设备重新安装kp证书，这是首次运行kp，生成kp证书用于https过滤的过程。

**Comment by tea1111980** [comment]
我重装了之后，就解决了，谢谢！我关帖了
