### ISSUE TITLE
R3安装ShadowSocks失败

### ISSUE THREAD

**Issue by KingHuaBo** [monlor/Monlor-Tools#7]
root@XiaoQiang:/# appmanage.sh  add ShadowSocks [-f]
【Tools】: 正在安装【ShadowSocks】在线插件...
【Tools】: 下载程序中...
【Tools】: 校验MD5文件信息
【Tools】: 下载【ShadowSocks】文件失败！
root@XiaoQiang:/#

**Comment by monlor** [comment]
安装方式不对，appmanage.sh add shadowsocks
或者运行monlor
