### ISSUE TITLE
建议增加resiliosync插件

### ISSUE THREAD

**Issue by lucky-beans** [monlor/Monlor-Tools#70]
Resiliosync官网提供安装包可以解压直接运行，工具箱加个新建虚拟内存和依赖库检查脚本就方便了

**Comment by monlor** [comment]
因为我只有R2D，R2D是系统自动建了256M虚拟内存的，然后R3经人测试内核不支持虚拟内存。依赖库检查？你说的ldd命令么，必要性不是很大。resiliosync在国内基本废了，可以考虑用verysync，要添加其实也不是不可以。

**Comment by lucky-beans** [comment]
额，其实主要是以前BTsync用的人多，共享key也多，客户端不太容易换

**Comment by monlor** [comment]
resilio不开源，官方编译的arm有很多问题，无法添加。
