### ISSUE TITLE
【已解决】SSR添加订阅有BUG了，有相同问题的可供参考一下

### ISSUE THREAD

**Issue by tea1111980** [monlor/Monlor-Tools#71]
# 细节1：
订阅列表可以正常获取，但是获取出来的代理列表无法全部添加到web选择列表里面，列表里面是空的，如果是URI一个个的添加，而且订阅添加只能选择其中一个使用，其它的全部没有添加进列表，而用web端SSR列表里也是空的，这是怎么回事？
添加了几遍，还是这样。
![image](https://user-images.githubusercontent.com/16295097/44275397-3479b700-a277-11e8-82dc-e77a8347068b.png)

![image](https://user-images.githubusercontent.com/16295097/44275597-ba95fd80-a277-11e8-98a4-7bbc8a048443.png)

**Comment by tea1111980** [comment]
不管清空之前的配置再添加，还是添加之前不清空配置，列表里面都是空的，只有使用URI方式一个个的添加的ssr://协议地址，SSR列表在web端里面才有显示，请问这是BUG吗？

**Comment by tea1111980** [comment]
无法订阅的，可以把curl升级到，如下图：

![image](https://user-images.githubusercontent.com/16295097/44276955-bcfa5680-a27b-11e8-879a-8ea172b2cdc1.png)

**Comment by monlor** [comment]
可以可以，就喜欢你这种喜欢自己解决问题的，是因为后面更新了订阅添加节点的方式，web还没来得及更新。

**Comment by tea1111980** [comment]
我不知道怎么在这个回复里面，把字体颜色弄成红色。。。。

**Comment by tea1111980** [comment]
能问一下，往小米后面Web里面添加功能这个在哪里有教程？
或者你闲的时候教教我也行。

**Comment by monlor** [comment]
额，其实做web我也不是很熟，主要是懒得学js，可以参考openwrt的开发教程再看看misstar tools的web代码。另外由于mardown不支持颜色？所以如果要改颜色有点麻烦，可能需要写html。

**Comment by tea1111980** [comment]
写了html也不行，直接呈现的是代码本身，没有被执行，哎，这个小问题就由它吧。。我去看看。谢谢了！

**Comment by monlor** [comment]
修改/etc/monlor/web/lua/api/monlor.lua，这个文件里面你可以搜索ssserver.conf，找到对应的代码，将其改成ssserver*.conf，修改完运行addweb即可。额，我有点懒了。

**Comment by tea1111980** [comment]
好吧，我试试

**Comment by tea1111980** [comment]
![image](https://user-images.githubusercontent.com/16295097/44295662-3a57b280-a2e0-11e8-914e-c0fd16d7b592.png)

速度还不错。。。Nice !

**Comment by monlor** [comment]
命令的科学上网等于按你设置的模式走代理，那是局域网设备控制，你可以直接设置其余设备科学上网就行了。这个跟你选什么模式没有关系。ss设置成全局确实会造成kp失效，这个我暂时解决不了。

**Comment by mklsw** [comment]
我的SSR 也无法自动更新地址  还在找资料看怎么更新Curl

@tea1111980   麻烦你能指导一下吗?

参考了这篇文章 ：https://www.cnblogs.com/suidouya/p/7387861.html  但卡在解压那了

**Comment by tea1111980** [comment]
@mklsw 
1. 你把monlor装在什么设备上？
2. 那个解压命令 参数那块不用加 -   直接 tar zxvf 你的压缩包全名  即可。

**Comment by tea1111980** [comment]
![image](https://user-images.githubusercontent.com/16295097/44305556-faaacc80-a3ac-11e8-8c69-b76eafadd22f.png)

@monlor   你看这个图上面扫描出来的设备列表，里面的地址172.16.26.0 这个段的，不是我的局域网，这些是什么设备？
还有最底下的 那一个超长的MAC地址是什么设备？

**Comment by tea1111980** [comment]
@mklsw  

```
#!/bin/ash

### 开读写权限
mkdir -p /userdisk/data/opt
mkdir -p /userdisk/data/opt/var/opkg-lists
mkdir -p /userdisk/data/opt/overlay
mount -o remount, rw /
cp -af /opt/* /userdisk/data/opt
cp -af /www/* /userdisk/data/opt/www
rm -rf /www
rm -rf /opt
ln -s /userdisk/data/opt/www /www
ln -s /userdisk/data/opt /opt

cat <<EOF >> /etc/profile
export PATH=/opt/bin:/opt/sbin:$PATH

if [ -f /userdisk/data/opt/root/.profile ]; then
       . /root/.profile
       . /opt/etc/profile
   else
       touch /root/.profile
       . /root/.profile
       . /opt/etc/profile
fi
EOF

chmod u+x /root/envenv.sh
./envenv.sh
ldconfig
cd /opt
wget http://pkg.entware.net/binaries/armv7/installer/entware_install.sh
chmod u+x entware_install.sh
./entware_install.sh


```


#########    把上面的那一大段代码保存到    /root/envenv.sh    文件后，就可以使用 opkg install curl  的形式安装了。

**Comment by mklsw** [comment]
@tea1111980   谢了 

折腾了2天 还是不会  先不管它了 先用手动配置

**Comment by monlor** [comment]
为啥不直接用工具箱里的entware呢，安装完重新登陆ssh，运行opkg install curl即可

**Comment by monlor** [comment]
可能还要加一句`alias curl=/opt/bin/curl`到环境变量文件，工具箱的/etc/monlor/config/profile，完了重新登陆ssh。

**Comment by monlor** [comment]
可能还要加一句`alias curl=/opt/bin/curl`到工具箱文件`/etc/monlor/scripts/base.sh`末尾。
