### ISSUE TITLE
chacha20-ietf-poly1305不支持

### ISSUE THREAD

**Issue by wy353208214** [monlor/Monlor-Tools#72]
chacha20-ietf-poly1305加密协议不支持，misstar tools是不支持的。
自定义添加规则的时候选了这个加密方式，但是添加之后全局模式无法运行启动

**Comment by wy353208214** [comment]
你可能理解错了，服务端就是以chacha20-ietf-poly1305作为加密协议的，我使用shadowsocks windos客户端是没问题的

**Comment by monlor** [comment]
`cat /var/log/shadowsocks.log`看看日志，可能mips的ss不支持那个加密协议。

**Comment by wy353208214** [comment]
好的，谢谢，晚上回去看下

**Comment by wy353208214** [comment]
另外，还有个问题，回国模式就是gfw模式吗？

**Comment by wy353208214** [comment]
哈哈，理解了，我一直以为gfw跟回国模式是一样的。谢谢~

**Comment by wy353208214** [comment]
建议建个群，大家进去讨论。
