### ISSUE TITLE
刚刚知道这个插件，请问支持R1D最新开发版吗？

### ISSUE THREAD

**Issue by ywyha** [monlor/Monlor-Tools#73]
我看R1D最近有更新开发版了，我还没有更新，因为看到说更新了不能支持MT工具箱，无意中看到了这个插件，不知道是否支持R1D最新开发版

希望能加入全系列插件的web安装 访问支持！大佬加油

**Comment by monlor** [comment]
支持的

**Comment by huos3203** [comment]
> 支持的

有可用的opkg索引库吗？在使用zerotier时，无法安装！
