### ISSUE TITLE
SSR新问题

### ISSUE THREAD

**Issue by tea1111980** [monlor/Monlor-Tools#75]
![image](https://user-images.githubusercontent.com/16295097/44628239-894fb880-a96e-11e8-8dcf-e24368d2d6cc.png)

只要我一重启我的路由器，就会提示上图所显示的链路异常，怎么弄？
我啥都没动，一重启就这样。

非要卸载该插件之后，把路由重启一遍，然后再安装，再输入订阅，再才能启动。

![image](https://user-images.githubusercontent.com/16295097/44628528-cb2f2d80-a973-11e8-9821-a27e8fe28866.png)

这是成功之后的画面。

**Comment by tea1111980** [comment]
@monlor  我还以为整个工具箱更新了呢，原来只是更新了SSR

**Comment by monlor** [comment]
建了没人加岂不是尴尬了😂，开个玩笑。等我折腾出个我满意的东西了再考虑建个TG群玩玩。

**Comment by tea1111980** [comment]
折腾出你满意的东西？啥东西啊？

**Comment by monlor** [comment]
额，我每隔一段时间统一处理。关于新的东西，不着急。

**Comment by tea1111980** [comment]
我突然想到，你可以申请一个小米开发者帐号，然后把你的工具箱做成小米固件的插件，这样就方便多了，交流也有地方了。

**Comment by tea1111980** [comment]
SSR这些禁止的东西，可以做为外挂再装，原生里面不调用。这样就不会查你了

**Comment by monlor** [comment]
关于这个，要是能做早有人做了，小米插件开发者的权限貌似很低，而且问题很多。

**Comment by tea1111980** [comment]
那小米的这个API这个功能就废了吗？

**Comment by tea1111980** [comment]
@monlor   koolproxy 这个出问题了，总是爱断网，把这个关掉就好了，怎么回事？

**Comment by tea1111980** [comment]
@monlor   SSR 又出现无法获取列表到 Web端了

**Comment by tea1111980** [comment]
@monlor  更新SSR 1.7.8 之后，列表还是空的。

**Comment by monlor** [comment]
额，这个我没更新，我更新一下吧

**Comment by tea1111980** [comment]
@monlor  好的，再问一下，如果问题被结束后，再在里面发言对方会收到吗？

**Comment by monlor** [comment]
应该会收到，最好@一下

**Comment by tea1111980** [comment]
好的，谢谢

**Comment by tea1111980** [comment]
@monlor  你这次更新工具箱的 SSR Web端列表的问题，解决了，可以显示了，哈哈！
