### ISSUE TITLE
Aria2 的问题

### ISSUE THREAD

**Issue by yinfei219** [monlor/Monlor-Tools#78]
作者你好,很感谢你能发布这么好用的工具箱,我刚接触
我是R2D,最新的开发版,之前有装Misstar Tools,前天直接刷了Monlor工具箱
安装了Aria2, entware和kodexplorer这3个工具, 都可以用
但是有个问题,aria2使用一段时间速度就降,能从5mb降到几十kb,然后就一直这么慢,过一段时间又能有个1mb,再过会路由就卡死,上不了网, cpu占用率100%,只能重启
不知道是不是aria2的问题

作者有群吗?

**Comment by monlor** [comment]
这个问题，我没出现过，没什么办法。

**Comment by yinfei219** [comment]
好吧,我再试试吧,现在我把它关了就好了
