### ISSUE TITLE
【已解决】启动SS出现Bad argument `address' Try `iptables -h' or 'iptables --help' for more information.

### ISSUE THREAD

**Issue by YongJie-Xie** [monlor/Monlor-Tools#79]
情况如下：
![tim 20180901105415](https://user-images.githubusercontent.com/29311669/44941771-12377b80-add7-11e8-92f0-e732b5cf725e.png)

经调试发现，是因为域名解析工具resolveip缺少-s参数，补上即可。

解决方案如下：
#vim /etc/monlor/apps/shadowsocks/script/shadowsocks.sh

大概在37行左右修改
原：ss_server_tmp=`resolveip $ss_server | head -1`
改：ss_server_tmp=`resolveip **-s** $ss_server | head -1`

![tim 20180901105527](https://user-images.githubusercontent.com/29311669/44941772-1a8fb680-add7-11e8-81a5-d20023a9d13d.png)

**Comment by tea1111980** [comment]
我的是要去掉这个 -s 的选项，我这个没有这个选项。

**Comment by YongJie-Xie** [comment]
@tea1111980 如果你启动没有报错，那就不需要理会，我也不知为何我这会出现这种情况，或许是resolveip升级了。如果跟我一样的错误信息，只要加上-s参数即可。

**Comment by YongJie-Xie** [comment]
补充一下，我的resolveip版本是2.3

**Comment by tea1111980** [comment]
resolveip 我的这个没有版本显示


![image](https://user-images.githubusercontent.com/16295097/44951893-82abce80-aea3-11e8-96ea-1438277ce44b.png)

**Comment by YongJie-Xie** [comment]
@tea1111980 也许我只是个例，参考即可。
![image](https://user-images.githubusercontent.com/29311669/45000564-9157ca00-aff8-11e8-94d2-312e172040cc.png)

**Comment by tea1111980** [comment]
@YongJie-Xie  你这个版本哪来的？ 我也装了Entware 可是最新的版本就是2.0的，没有2.3的
