### ISSUE TITLE
v.2.1.18 can't install anything

### ISSUE THREAD

**Issue by farhanito** [monlor/Monlor-Tools#8]
请输入你的选择(exit退出)：3

确定要安装aria2插件？[1/0] 1
【Tools】: 正在安装【aria2】在线插件...
【Tools】: 下载程序中...
【Tools】: 校验MD5文件信息
【Tools】: 下载【aria2】文件失败！
返回主菜单？[1/0]

**Comment by monlor** [comment]
sorry, I'll fix it right away!

**Comment by monlor** [comment]
thanks for your issue, it's ok now.

**Comment by farhanito** [comment]
thank you. excellent
