### ISSUE TITLE
如何自动更新黑白名单？

### ISSUE THREAD

**Issue by lzj1121** [monlor/Monlor-Tools#80]
能不能在插件中加入自动更新黑白名单的选项，或者能否简明告知如何替换名单，感谢！现有名单有点问题……

**Comment by monlor** [comment]
额，是有点问题，在/etc/monlor/apps/shadowsocks/script

**Comment by lzj1121** [comment]
我看到您的更新源有些问题，可我换成https://github.com/hq450/fancyss/tree/master/rules以后貌似整个就崩盘了=。=

**Comment by lzj1121** [comment]
现在ks的ss整体移到这里了…

**Comment by monlor** [comment]
我今天有时间更新一下规则地址

**Comment by lzj1121** [comment]
您更新完稍微测试一下，我手动./更新规则以后路由就崩了，不知道啥原因

**Comment by lzj1121** [comment]
@monlor 这次更新以后，黑白名单还是有一些不太合适的地方，比如说用到白名单，一些走国内更快的地址就奇奇怪怪的变得很慢，比如说iCloud云上贵州服务器，用白名单上传云备份上传速度几乎为0，在比如说苹果imassage信息发送图片给对方，几乎要走十几分钟才能发出，或者发送失败根本发不出去，然后我改到黑名单模式gfwlist里，云上贵州走国内上传很快，imassage发图也很快，但是一些小众的国外被墙网站就不在名单里无法浏览加速，所以，很苦恼....,.,.

**Comment by monlor** [comment]
关于这个只能自行取舍了，建议黑名单，不能访问的网站手动添加到自定义规则。

**Comment by monlor** [comment]
ss规则地址已更新了
