### ISSUE TITLE
为什么使用黑名单模式，国内网站仍然是走ssr呢？

### ISSUE THREAD

**Issue by cokei2008** [monlor/Monlor-Tools#81]
非常感谢作者的强大插件，作为小白有一个问题，黑名单模式其实就是gfwlist模式，为什么没有自动绕过国内网站呢？需要怎么设置呢？

**Comment by monlor** [comment]
黑名单即gfwlist模式，白名单模式即为绕过国内网站

**Comment by cokei2008** [comment]
还有一个问题，好像类似bug似的，以访问google为例，有时候黑名单模式打不开google，切换到白名单就行，有时候白名单不行再切换回黑名单又好了。

**Comment by monlor** [comment]
可能有dns污染的问题，可以尝试把你访问的谷歌网址添加到黑名单试试。
