### ISSUE TITLE
大佬，这个看起来有点屌啊

### ISSUE THREAD

**Issue by lzj1121** [monlor/Monlor-Tools#83]
不是Bug report，ks最近加的这个功能看起来有些屌啊，给大佬分享一下，看评价下来非常不错，自己技术不够，如果大佬有时间了研究一下……
![jietu20180906-112216 2x](https://user-images.githubusercontent.com/42904862/45133384-79827080-b1c7-11e8-9acb-8d17dec580cc.jpg)
以下是提供的网页地址：
https://www.v2ex.com/t/172010
https://github.com/infinet/dnsmasq
http://koolshare.cn/thread-65484-1-1.html

**Comment by monlor** [comment]
这个需要远程测试，有兴趣的话加我QQ：421599756

**Comment by tea1111980** [comment]
@lzj1121  你给出的这个kool网站里面的下载不了。
