### ISSUE TITLE
vsftpd有问题 无法启动

### ISSUE THREAD

**Issue by hengsuyu** [monlor/Monlor-Tools#84]
小米路由器3G 安装vsftpd会导致root用户丢失 无法登陆ssh monlor版本2.9.4

**Comment by monlor** [comment]
ftp添加用户时，请确认别添加`root`用户

**Comment by tea1111980** [comment]
@monlor 大佬，有没有想法，把其它应用也加入Web端啊？

**Comment by monlor** [comment]
@tea1111980 当前的版本不会再更新web，正在计划新的东西。

**Comment by monlor** [comment]
@tea1111980 你可以加一下TG群，到时候有啥计划也会在群里通知。web这方面有兴趣的话，照葫芦画瓢，其他插件也很容易做出来。

**Comment by tea1111980** [comment]
@monlor 哪里有TG群？
