### ISSUE TITLE
小米路由器mini最新开发版本安装出错

### ISSUE THREAD

**Issue by PiktCai** [monlor/Monlor-Tools#88]
Welcome to Monlor Tools!  
【Tools】: 请按任意键安装工具箱(Ctrl + C 退出).

【Tools】: 请选择安装方式(1.内置储存 2.外置储存 3.内存安装) 
3
【Tools】: 内存安装占用内存多，重启会自动更新工具箱和插件(回车继续).

【Tools】: 下载工具箱文件...
【Tools】: 解压工具箱文件
cp: write error: No space left on device
cp: can't create '/etc/monlor/web/img/icon-shadowsocks-bg.png': No space left on device
cp: can't create '/etc/monlor/web/img/icon-koolproxy.png': No space left on device
cp: can't create '/etc/monlor/web/img/icon-koolproxy-bg.png': No space left on device
cp: can't preserve permissions of '/etc/monlor/web/img': No space left on device
cp: can't create directory '/etc/monlor/web/htm': No space left on device
cp: can't create directory '/etc/monlor/web/css': No space left on device
cp: can't preserve permissions of '/etc/monlor/web': No space left on device
cp: can't create directory '/etc/monlor/scripts': No space left on device
cp: can't create '/etc/monlor/newinfo.txt': No space left on device
cp: can't create directory '/etc/monlor/config': No space left on device
cp: can't create directory '/etc/monlor/apps': No space left on device
cp: can't preserve permissions of '/etc/monlor': No space left on device
chmod: /etc/monlor/web: No space left on device
chmod: /etc/monlor/web: No space left on device
touch: /etc/monlor/config/applist.txt: No such file or directory
【Tools】: 初始化工具箱...
touch: /etc/config/monlor: No space left on device
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
sh: /etc/monlor/scripts/init.sh: not found
【Tools】: 工具箱安装完成!
【Tools】: 运行monlor命令即可配置工具箱
root@XiaoQiang:~# monlor
-ash: monlor: not found

**Comment by monlor** [comment]
建议使用外置储存安装

**Comment by PiktCai** [comment]
> 建议使用外置储存安装

好的，现已安装成功

**Comment by cloverstd** [comment]
@monlor 选择外置储存貌似也会在 /etc 下创建配置文件
```
Filesystem                Size      Used Available Use% Mounted on
rootfs                   10.8M     10.8M         0 100% /
/dev/root                10.8M     10.8M         0 100% /
tmpfs                    61.0M      2.2M     58.8M   4% /tmp
tmpfs                   512.0K         0    512.0K   0% /dev
tmpfs                    61.0M      2.2M     58.8M   4% /extdisks
/dev/mtdblock7            1.0M    956.0K     68.0K  93% /data
/dev/mtdblock7            1.0M    956.0K     68.0K  93% /etc
tmpfs                    61.0M      2.2M     58.8M   4% /userdisk/sysapihttpd
/dev/root                 1.0M    956.0K     68.0K  93% /mnt
/dev/mtdblock7            1.0M    956.0K     68.0K  93% /mnt
/dev/sda1                 1.8G    102.3M      1.7G   5% /extdisks/sda1
```
/etc 貌似不能写

**Comment by monlor** [comment]
选外置储存不会在etc下创建文件吧

**Comment by cloverstd** [comment]
@monlor 

```
root@XiaoQiang:~# sh -c "$(curl -kfsSl https://coding.net/u/monlor/p/Monlor-Tools/git/raw/master/install.sh)" && source
/etc/profile &> /dev/null
***********************************************
**                                           **
**          Welcome to Monlor Tools!         **
**                                           **
***********************************************
【Tools】: 请按任意键安装工具箱(Ctrl + C 退出).

【Tools】: 请选择安装方式(1.内置储存 2.外置储存 3.内存安装)
2
【Tools】: 工具箱已安装，是否覆盖？[1/0]
1
【Tools】: 下载工具箱文件...
【Tools】: 解压工具箱文件
【Tools】: 初始化工具箱...
touch: /etc/config/monlor: No space left on device
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
cp: can't stat '/etc/monlor/config/monlor.uci': No such file or directory
uci: Entry not found
uci: Entry not found
uci: Entry not found
/extdisks/sda1/.monlor/scripts/init.sh: source: line 36: can't open '/etc/monlor/scripts/base.sh'
【Tools】: 工具箱安装完成!
【Tools】: 运行monlor命令即可配置工具箱
root@XiaoQiang:~#
```

**Comment by monlor** [comment]
额，这个是必须得创建的文件，如果这点空间都没有的话，建议你重置一下系统，尝试能否安装。

**Comment by cloverstd** [comment]
@monlor 我是刚刚刷的开发版，理论上里面应该啥也没有才对
