### ISSUE TITLE
安装Shadowsocks成功，但是配置好像出错呢。

### ISSUE THREAD

**Issue by adgvcxz** [monlor/Monlor-Tools#9]
进入shadowsocks高级设置？[1/0] 0
/etc/monlor/scripts/monlor: line 430: /etc/monlor/apps/shadowsocks/script/shadowsocks.sh: not found
返回主菜单？[1/0]

**Comment by monlor** [comment]
设备型号？/etc/monlor/apps/shadowsocks/script/shadowsocks.sh status运行试试。

**Comment by wanghurui** [comment]
r3 shadowsocks用不了，用客户端就没有问题，是不是被和谐了

**Comment by monlor** [comment]
因为没有r3路由器，我无法测试这个插件。所以不能保证运行正常。
