### ISSUE TITLE
请教一下， 我开启SS之后， 路由器无法上网。

### ISSUE THREAD

**Issue by MQL9011** [monlor/Monlor-Tools#97]
我的SS是可以的， 因为电脑上也用的同一个SS地址。 电脑SS翻墙没问题。
 
在路由器上配置过SS之后， 用同样的上网模式， 发现路由器连不上网。

**Comment by MQL9011** [comment]
![image](https://user-images.githubusercontent.com/11871158/48781710-88cd8080-ed17-11e8-9f74-50e66d66a84f.png)

**Comment by Garriot** [comment]
我也遇到了这个问题。 科学上网模式不行，但是全局模式可以。
